/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Войти по email/паролю */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Успешный вход. Refresh-токен ставится в httpOnly cookie. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Неверный email/пароль (code=invalid_credentials) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /**
                 * @description Аккаунт временно заблокирован после неудачных попыток (code=account_locked)
                 *     или деактивирован (code=user_inactive)
                 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить access-токен по refresh-cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Новый access-токен. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выйти (отозвать refresh-токен) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль текущего пользователя */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пользователей */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Все пользователи (без пагинации — справочник) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        /** Создать пользователя */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description Email уже существует */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить пользователя (мягкое удаление) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Обновить пользователя */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description User */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список клиентов */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: components["schemas"]["ClientStatus"];
                    accountManagerId?: components["schemas"]["UUID"];
                    industry?: string;
                    clientKind?: components["schemas"]["ClientKind"];
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Страница клиентов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientPage"];
                    };
                };
            };
        };
        put?: never;
        /** Создать клиента */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateClientRequest"];
                };
            };
            responses: {
                /** @description Client */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Клиент по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Удалить клиента (soft-delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Обновить клиента */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateClientRequest"];
                };
            };
            responses: {
                /** @description Client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/clients/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Контакты клиента */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Контакты */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contact"][];
                    };
                };
            };
        };
        put?: never;
        /** Добавить контакт клиенту */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateContactRequest"];
                };
            };
            responses: {
                /** @description Contact */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contact"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список контактов всех клиентов */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    clientId?: components["schemas"]["UUID"];
                    hasEmail?: boolean;
                    hasPhone?: boolean;
                    hasTelegram?: boolean;
                    hasBirthday?: boolean;
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Страница контактов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContactListItemPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Контакт по id (с названием клиента) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ContactListItem */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContactListItem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Удалить контакт */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Обновить контакт */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateContactRequest"];
                };
            };
            responses: {
                /** @description ContactListItem */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContactListItem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список вакансий с фильтрами */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: components["schemas"]["VacancyStatus"];
                    clientId?: components["schemas"]["UUID"];
                    grade?: components["schemas"]["Grade"];
                    priority?: components["schemas"]["Priority"];
                    recruiterId?: components["schemas"]["UUID"];
                    accountManagerId?: components["schemas"]["UUID"];
                    engagementType?: components["schemas"]["EngagementType"];
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Страница вакансий */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacancyPage"];
                    };
                };
            };
        };
        put?: never;
        /** Создать вакансию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateVacancyRequest"];
                };
            };
            responses: {
                /** @description Vacancy */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vacancy"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/kanban-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Пакетное обновление порядка карточек на канбане */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        updates: {
                            id: components["schemas"]["UUID"];
                            status: components["schemas"]["VacancyStatus"];
                            kanbanOrder: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Обновлённые вакансии */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vacancy"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карта разрешённых переходов между статусами вакансии
         * @description Возвращает словарь `transitions` { fromStatus: [allowedTo...] } и
         *     список финальных статусов (для них смена статуса требует комментария).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transitions config */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransitionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/parse-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI-парсинг сплошного текста брифа в структурированные поля */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Распознанные поля вакансии */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            parsed: components["schemas"]["ParsedVacancy"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Вакансия по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vacancy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vacancy"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Удалить вакансию (soft-delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Обновить вакансию */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateVacancyRequest"];
                };
            };
            responses: {
                /** @description Vacancy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vacancy"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/vacancies/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Сменить статус вакансии (с валидацией перехода и опциональным комментарием) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["VacancyStatus"];
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Vacancy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vacancy"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Недопустимый переход / отсутствует обязательный комментарий */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/vacancies/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Активность по вакансии */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Прикреплённые к вакансии кандидаты */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description matches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacancyCandidate"][];
                    };
                };
            };
        };
        put?: never;
        /** Прикрепить кандидата к вакансии (идемпотентно) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        candidateId: components["schemas"]["UUID"];
                    };
                };
            };
            responses: {
                /** @description Match (новый или существующий) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacancyCandidate"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Тип кандидата не совпадает с типом вакансии (engagement_type_mismatch) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID match-связки (UUID или синтетический `m-{vacancyId}-{candidateId}` в MSW) */
                matchId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Открепить кандидата от вакансии */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID match-связки (UUID или синтетический `m-{vacancyId}-{candidateId}` в MSW) */
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Сменить статус match */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID match-связки (UUID или синтетический `m-{vacancyId}-{candidateId}` в MSW) */
                    matchId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["MatchStatus"];
                        feedback?: string;
                    };
                };
            };
            responses: {
                /** @description VacancyCandidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VacancyCandidate"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список кандидатов */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    status?: components["schemas"]["CandidateStatus"];
                    grade?: components["schemas"]["Grade"];
                    recruiterId?: components["schemas"]["UUID"];
                    stack?: string;
                    engagementType?: components["schemas"]["EngagementType"];
                    employmentType?: components["schemas"]["EmploymentType"];
                    /** @description false (по умолчанию) — только активные на доске; true — только архивные; "all" — оба. */
                    archived?: boolean | "all";
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Страница кандидатов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandidatePage"];
                    };
                };
            };
        };
        put?: never;
        /** Создать кандидата */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCandidateRequest"];
                };
            };
            responses: {
                /** @description Candidate */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                /** @description Дубликат по email/phone */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/kanban-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Пакетное обновление порядка карточек кандидатов */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        updates: {
                            id: components["schemas"]["UUID"];
                            status: components["schemas"]["CandidateStatus"];
                            kanbanOrder: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Обновлённые кандидаты */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Кандидат по id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Удалить кандидата. По умолчанию — soft-archive (убирает с канбана,
         *     оставляет в базе). С `?permanent=true` — полное удаление (admin only).
         */
        delete: {
            parameters: {
                query?: {
                    permanent?: boolean;
                };
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Обновить кандидата */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCandidateRequest"];
                };
            };
            responses: {
                /** @description Candidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/candidates/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Сменить статус кандидата */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["CandidateStatus"];
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Candidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Недопустимый переход */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/candidates/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Убрать кандидата с канбан-доски (в архив) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Candidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вернуть кандидата на доску */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candidate"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candidates/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Активность по кандидату */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Активность по клиенту */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Activity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Комментарии к сущности */
        get: {
            parameters: {
                query: {
                    entityType: components["schemas"]["CommentEntityType"];
                    entityId: components["schemas"]["UUID"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список комментариев (с ответами) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put?: never;
        /** Создать комментарий */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCommentRequest"];
                };
            };
            responses: {
                /** @description Comment */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить комментарий (автор / admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Редактировать комментарий (автор) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCommentRequest"];
                };
            };
            responses: {
                /** @description Comment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Comment"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Уведомления пользователя */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список уведомлений */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Отметить уведомление прочитанным */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отметить все прочитанными */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал аудита с фильтрами */
        get: {
            parameters: {
                query?: {
                    entityType?: string;
                    entityId?: components["schemas"]["UUID"];
                    actorId?: components["schemas"]["UUID"];
                    field?: string;
                    dateFrom?: string;
                    dateTo?: string;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Аудит */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка дашборда */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description DashboardSummary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Воронка по статусам вакансий */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description FunnelBucket[] */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FunnelBucket"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/recruiter-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Нагрузка рекрутеров */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description RecruiterLoad[] */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecruiterLoad"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Получить presigned URL для загрузки файла в S3 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PresignRequest"];
                };
            };
            responses: {
                /** @description PresignResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresignResponse"];
                    };
                };
                /** @description Неподдерживаемый MIME или превышен размер (unsupported_mime / file_too_large) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подтвердить загрузку (создаёт запись в БД, ставит scan_status=pending) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description FileResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Файлы сущности */
        get: {
            parameters: {
                query: {
                    entityType: components["schemas"]["FileEntityType"];
                    entityId: components["schemas"]["UUID"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список файлов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        /** Временный URL для скачивания */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description DownloadResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DownloadResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Файл найден антивирусом как заражённый (file_infected) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UuidPathId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить файл (владелец или admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UuidPathId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Матрица прав */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Матрица */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["MatrixPermission"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions-matrix/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Обновить строку матрицы (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Словарь { role: boolean } */
                        matrix: {
                            [key: string]: boolean;
                        };
                    };
                };
            };
            responses: {
                /** @description MatrixPermission */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatrixPermission"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions-matrix/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сбросить матрицу к дефолту (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Матрица */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["MatrixPermission"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        UUID: string;
        ApiError: {
            /** @description Машиночитаемый код, например engagement_type_mismatch */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenResponse: {
            accessToken: string;
            refreshToken: string;
        };
        /** @enum {string} */
        Role: "admin" | "account_manager" | "recruiter" | "viewer";
        User: {
            id: components["schemas"]["UUID"];
            /** Format: email */
            email: string;
            telegram?: string | null;
            fullName: string;
            role: components["schemas"]["Role"];
            initials: string;
            color: string;
            isActive: boolean;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            telegram?: string;
            fullName: string;
            role: components["schemas"]["Role"];
            password?: string;
            isActive?: boolean;
        };
        UpdateUserRequest: {
            /** Format: email */
            email?: string;
            telegram?: string | null;
            fullName?: string;
            role?: components["schemas"]["Role"];
            isActive?: boolean;
        };
        /** @enum {string} */
        ClientStatus: "lead" | "in_progress" | "active" | "paused" | "archived";
        /**
         * @description Прямой клиент / посредник
         * @enum {string}
         */
        ClientKind: "direct" | "intermediary";
        LegalEntity: {
            id: components["schemas"]["UUID"];
            name: string;
            inn: string;
        };
        Client: {
            id: components["schemas"]["UUID"];
            name: string;
            legalEntities: components["schemas"]["LegalEntity"][];
            industry: string;
            accountManagerId: components["schemas"]["UUID"];
            status: components["schemas"]["ClientStatus"];
            clientKind: components["schemas"]["ClientKind"];
            telegramChat?: string | null;
            vacanciesCount: number;
            contactsCount: number;
        };
        CreateClientRequest: {
            name: string;
            legalEntities?: {
                id?: components["schemas"]["UUID"];
                name: string;
                inn: string;
            }[];
            industry: string;
            accountManagerId: components["schemas"]["UUID"];
            status: components["schemas"]["ClientStatus"];
            clientKind: components["schemas"]["ClientKind"];
            telegramChat?: string;
        };
        /** @description Все поля опциональны (Partial<Client>) */
        UpdateClientRequest: components["schemas"]["CreateClientRequest"] & Record<string, never>;
        Contact: {
            id: components["schemas"]["UUID"];
            clientId: components["schemas"]["UUID"];
            name: string;
            role: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            telegram?: string | null;
            /**
             * Format: date
             * @description ISO date YYYY-MM-DD
             */
            birthday?: string | null;
        };
        ContactListItem: components["schemas"]["Contact"] & {
            clientName: string;
        };
        CreateContactRequest: {
            name: string;
            role: string;
            /** Format: email */
            email?: string;
            phone?: string;
            telegram?: string;
            /** Format: date */
            birthday?: string;
        };
        /** @enum {string} */
        Grade: "Junior" | "Middle" | "Senior" | "Lead";
        /** @enum {string} */
        WorkFormat: "Удалённо" | "Гибрид" | "Офис";
        /** @enum {string} */
        Priority: "low" | "medium" | "high" | "urgent";
        /**
         * @description Тип сделки/кандидата
         * @enum {string}
         */
        EngagementType: "outstaff" | "agency";
        /** @enum {string} */
        VacancyStatus: "new" | "in_work" | "proposed" | "interview" | "waiting_os" | "closed_success" | "closed" | "paused";
        Vacancy: {
            id: components["schemas"]["UUID"];
            title: string;
            clientId: components["schemas"]["UUID"];
            engagementType: components["schemas"]["EngagementType"];
            project?: string | null;
            grade: components["schemas"]["Grade"];
            stack: string[];
            format: components["schemas"]["WorkFormat"];
            /** @description ₽/час */
            rateClient: number;
            /** @description ₽/мес, агентство */
            salaryMax?: number | null;
            positions: number;
            status: components["schemas"]["VacancyStatus"];
            priority: components["schemas"]["Priority"];
            accountManagerId: components["schemas"]["UUID"];
            recruiterIds: components["schemas"]["UUID"][];
            daysInStatus: number;
            candidatesCount: number;
            /** Format: date */
            deadline?: string | null;
            kanbanOrder: number;
            description?: string | null;
            requirements?: string | null;
        };
        CreateVacancyRequest: {
            title: string;
            clientId: components["schemas"]["UUID"];
            engagementType: components["schemas"]["EngagementType"];
            project?: string;
            grade: components["schemas"]["Grade"];
            stack?: string[];
            format: components["schemas"]["WorkFormat"];
            rateClient?: number;
            salaryMax?: number | null;
            positions: number;
            status: components["schemas"]["VacancyStatus"];
            priority: components["schemas"]["Priority"];
            accountManagerId: components["schemas"]["UUID"];
            recruiterIds?: components["schemas"]["UUID"][];
            /** Format: date */
            deadline?: string | null;
            description?: string;
            requirements?: string;
        };
        /** @description Partial<Vacancy> */
        UpdateVacancyRequest: components["schemas"]["CreateVacancyRequest"] & Record<string, never>;
        TransitionsResponse: {
            /** @description Словарь { fromStatus: [allowedTo...] } */
            transitions: {
                [key: string]: components["schemas"]["VacancyStatus"][];
            };
            finalStatuses: components["schemas"]["VacancyStatus"][];
        };
        ParsedVacancy: {
            title?: string;
            project?: string;
            grade?: components["schemas"]["Grade"];
            format?: components["schemas"]["WorkFormat"];
            priority?: components["schemas"]["Priority"];
            rateClient?: number;
            /** Format: date */
            deadline?: string;
            /** @description CSV-список технологий */
            stack?: string;
            description?: string;
            requirements?: string;
        };
        /** @enum {string} */
        CandidateStatus: "new" | "recruiter_iv" | "ready" | "presented" | "waiting_os" | "offer" | "rejected_client" | "rejected_candidate" | "hired" | "reserve";
        /** @enum {string} */
        EmploymentType: "ИП" | "СМЗ" | "ТК РФ";
        /** @enum {string} */
        LanguageLevel: "A1" | "A2" | "B1" | "B2" | "C1" | "C2" | "родной";
        SkillCategory: {
            id: string;
            name: string;
            items: string[];
        };
        CandidateExperience: {
            id: string;
            company: string;
            position: string;
            /** @description YYYY-MM */
            startMonth: string;
            /** @description YYYY-MM или null = «по настоящее время» */
            endMonth?: string | null;
            project?: string;
            achievements: string[];
            stack: string[];
        };
        CandidateEducation: {
            id: string;
            degree: string;
            institution: string;
            city?: string;
            graduationYear: number;
            specialty?: string;
        };
        CandidateCertification: {
            id: string;
            title: string;
            issuer: string;
            period?: string;
        };
        CandidateLanguage: {
            language: string;
            level: components["schemas"]["LanguageLevel"];
        };
        Candidate: {
            id: components["schemas"]["UUID"];
            fullName: string;
            role: string;
            engagementType: components["schemas"]["EngagementType"];
            grade: components["schemas"]["Grade"];
            experienceYears: number;
            stack: string[];
            /** @description ₽/мес. Скрыто для ролей без прав на чувствительные поля. */
            rateMonth: number | null;
            employmentType: components["schemas"]["EmploymentType"];
            format: components["schemas"]["WorkFormat"];
            location: string;
            recruiterId: components["schemas"]["UUID"];
            status: components["schemas"]["CandidateStatus"];
            daysInStatus: number;
            vacancyIds: components["schemas"]["UUID"][];
            telegram?: string | null;
            /** @description Скрыто для ролей без прав */
            phone?: string | null;
            /**
             * Format: email
             * @description Скрыто для ролей без прав
             */
            email?: string | null;
            /** Format: date */
            birthday?: string | null;
            kanbanOrder: number;
            summary?: string;
            skillCategories?: components["schemas"]["SkillCategory"][];
            experience?: components["schemas"]["CandidateExperience"][];
            education?: components["schemas"]["CandidateEducation"][];
            certifications?: components["schemas"]["CandidateCertification"][];
            languages?: components["schemas"]["CandidateLanguage"][];
            archived?: boolean;
            /** Format: date-time */
            archivedAt?: string | null;
            archivedById?: components["schemas"]["UUID"] | null;
            archiveReason?: string;
        };
        CreateCandidateRequest: {
            fullName: string;
            role: string;
            engagementType: components["schemas"]["EngagementType"];
            grade: components["schemas"]["Grade"];
            experienceYears?: number;
            stack?: string[];
            rateMonth?: number;
            employmentType: components["schemas"]["EmploymentType"];
            format: components["schemas"]["WorkFormat"];
            location?: string;
            recruiterId?: components["schemas"]["UUID"];
            status?: components["schemas"]["CandidateStatus"];
            telegram?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            /** Format: date */
            birthday?: string;
            summary?: string;
            skillCategories?: components["schemas"]["SkillCategory"][];
            experience?: components["schemas"]["CandidateExperience"][];
            education?: components["schemas"]["CandidateEducation"][];
            certifications?: components["schemas"]["CandidateCertification"][];
            languages?: components["schemas"]["CandidateLanguage"][];
        };
        /** @description Partial<Candidate> */
        UpdateCandidateRequest: components["schemas"]["CreateCandidateRequest"] & Record<string, never>;
        /** @enum {string} */
        MatchStatus: "submitted" | "reviewed" | "interview" | "offered" | "accepted" | "rejected_client" | "rejected_internal";
        VacancyCandidate: {
            /** @description UUID или синтетический id в моках */
            id: string;
            vacancyId: components["schemas"]["UUID"];
            candidateId: components["schemas"]["UUID"];
            status: components["schemas"]["MatchStatus"];
            addedById: components["schemas"]["UUID"];
            /** Format: date-time */
            addedAt: string;
            feedback?: string | null;
        };
        /** @enum {string} */
        CommentEntityType: "contact" | "candidate" | "vacancy" | "client";
        Comment: {
            id: components["schemas"]["UUID"];
            entityType: components["schemas"]["CommentEntityType"];
            entityId: components["schemas"]["UUID"];
            authorId: components["schemas"]["UUID"];
            parentId: components["schemas"]["UUID"] | null;
            text: string;
            mentions: components["schemas"]["UUID"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string | null;
        };
        CreateCommentRequest: {
            entityType: components["schemas"]["CommentEntityType"];
            entityId: components["schemas"]["UUID"];
            text: string;
            parentId?: components["schemas"]["UUID"] | null;
            mentions?: components["schemas"]["UUID"][];
        };
        UpdateCommentRequest: {
            text: string;
            mentions?: components["schemas"]["UUID"][];
        };
        Notification: {
            id: components["schemas"]["UUID"];
            userId: components["schemas"]["UUID"];
            /** @enum {string} */
            kind: "mention" | "status_change" | "system";
            text: string;
            /** @enum {string|null} */
            entityType?: "vacancy" | "candidate" | "client" | "contact" | null;
            entityId?: components["schemas"]["UUID"] | null;
            read: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ActivityEntry: {
            id: components["schemas"]["UUID"];
            /** @enum {string} */
            entityType: "vacancy" | "candidate" | "client";
            entityId: components["schemas"]["UUID"];
            actorId: components["schemas"]["UUID"];
            /** @enum {string} */
            kind: "create" | "status" | "note" | "call" | "email";
            text: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuditEntry: {
            id: components["schemas"]["UUID"];
            entityType: string;
            entityId: components["schemas"]["UUID"];
            actorId: components["schemas"]["UUID"];
            field: string;
            before: string | null;
            after: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        DashboardSummary: {
            openVacancies: number;
            activeCandidates: number;
            closedThisMonth: number;
            hiredThisMonth: number;
            delta: {
                openVacancies: number;
                activeCandidates: number;
                closedThisMonth: number;
                hiredThisMonth: number;
            };
        };
        FunnelBucket: {
            status: components["schemas"]["VacancyStatus"];
            count: number;
        };
        RecruiterLoad: {
            recruiterId: components["schemas"]["UUID"];
            activeCount: number;
        };
        /** @enum {string} */
        FileEntityType: "candidate" | "vacancy" | "client" | "contact";
        /** @enum {string} */
        ScanStatus: "pending" | "clean" | "infected" | "error";
        FileResponse: {
            id: components["schemas"]["UUID"];
            ownerUserId: components["schemas"]["UUID"];
            entityType: components["schemas"]["FileEntityType"];
            entityId: components["schemas"]["UUID"];
            fileKey: string;
            originalName: string;
            mime: string;
            /** Format: int64 */
            size: number;
            scanStatus: components["schemas"]["ScanStatus"];
            /** Format: date-time */
            scannedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PresignRequest: {
            entityType: components["schemas"]["FileEntityType"];
            entityId: components["schemas"]["UUID"];
            originalName: string;
            mime: string;
            size: number;
        };
        PresignResponse: {
            url: string;
            fields: {
                [key: string]: string;
            };
            fileKey: string;
            maxBytes: number;
        };
        ConfirmRequest: {
            fileKey: string;
            entityType: components["schemas"]["FileEntityType"];
            entityId: components["schemas"]["UUID"];
            originalName: string;
            mime: string;
            size: number;
        };
        DownloadResponse: {
            url: string;
            expiresIn: number;
        };
        MatrixPermission: {
            id: string;
            group: string;
            permission: string;
            description: string;
            actions: string[];
            /** @description Словарь { role: boolean } по всем ролям. */
            matrix: {
                [key: string]: boolean;
            };
        };
        Page: {
            items: unknown[];
            total: number;
            page: number;
            pageSize: number;
        };
        ClientPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Client"][];
        };
        ContactListItemPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["ContactListItem"][];
        };
        VacancyPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Vacancy"][];
        };
        CandidatePage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Candidate"][];
        };
    };
    responses: {
        /** @description OK */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @enum {boolean} */
                    ok: true;
                };
            };
        };
        /** @description Не авторизован */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Нет прав */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Слишком много запросов */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        UuidPathId: components["schemas"]["UUID"];
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
