// Notion-style emoji picker dataset.
// Содержит 700+ эмодзи с русскими и английскими ключевыми словами для поиска.
// Структура близка к unicode-emoji-json, но компактнее и без сторонних зависимостей.

export interface Emoji {
  c: string; // character
  n: string; // name (рус.) — показывается в подсказке
  k: string; // keywords для поиска (через пробел, строчные)
}

export interface EmojiCategory {
  id: string;
  title: string;
  icon: string; // эмодзи-таб
  items: Emoji[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    title: 'Смайлы и эмоции',
    icon: '😀',
    items: [
      { c: '😀', n: 'Улыбка', k: 'улыбка smile happy face радость' },
      { c: '😃', n: 'Радость', k: 'радость smile happy' },
      { c: '😄', n: 'Смех', k: 'смех laugh happy' },
      { c: '😁', n: 'Сияющая улыбка', k: 'улыбка grin' },
      { c: '😆', n: 'Хохот', k: 'смех laugh lol' },
      { c: '😅', n: 'Пот от смеха', k: 'смех sweat relief' },
      { c: '🤣', n: 'Катаюсь от смеха', k: 'смех rofl' },
      { c: '😂', n: 'Слёзы от смеха', k: 'смех joy слезы' },
      { c: '🙂', n: 'Лёгкая улыбка', k: 'улыбка slight smile' },
      { c: '🙃', n: 'Перевёрнут', k: 'sarcasm upside ирония' },
      { c: '😉', n: 'Подмигиваю', k: 'wink подмигивание' },
      { c: '😊', n: 'Стесняюсь', k: 'blush стеснение' },
      { c: '😇', n: 'Ангел', k: 'angel святой ангел' },
      { c: '🥰', n: 'Влюблён', k: 'love сердечки' },
      { c: '😍', n: 'Сердца в глазах', k: 'love heart eyes' },
      { c: '🤩', n: 'Звёзды в глазах', k: 'star struck wow' },
      { c: '😘', n: 'Воздушный поцелуй', k: 'kiss поцелуй' },
      { c: '😋', n: 'Вкусно', k: 'yum вкусно' },
      { c: '😎', n: 'В очках', k: 'cool солнцезащитные' },
      { c: '🤓', n: 'Ботаник', k: 'nerd очки' },
      { c: '🧐', n: 'С моноклем', k: 'monocle думает' },
      { c: '🤔', n: 'Думаю', k: 'thinking думаю' },
      { c: '🤨', n: 'Скептик', k: 'raised eyebrow' },
      { c: '😐', n: 'Без эмоций', k: 'neutral neutral' },
      { c: '😑', n: 'Безразличие', k: 'expressionless' },
      { c: '😶', n: 'Без рта', k: 'no mouth' },
      { c: '🙄', n: 'Закатил глаза', k: 'eye roll' },
      { c: '😏', n: 'Хитрая улыбка', k: 'smirk' },
      { c: '😣', n: 'Сдержанно', k: 'persevere' },
      { c: '😥', n: 'Огорчён', k: 'disappointed relieved' },
      { c: '😮', n: 'Удивлён', k: 'open mouth wow' },
      { c: '🤐', n: 'Молчу', k: 'zipped mouth' },
      { c: '😯', n: 'Hushed', k: 'тише' },
      { c: '😪', n: 'Сонный', k: 'sleepy спать' },
      { c: '😫', n: 'Устал', k: 'tired устал' },
      { c: '🥱', n: 'Зеваю', k: 'yawn' },
      { c: '😴', n: 'Сплю', k: 'sleeping' },
      { c: '😌', n: 'Облегчение', k: 'relieved' },
      { c: '😛', n: 'Язык', k: 'tongue stuck out' },
      { c: '🤤', n: 'Слюнки', k: 'drooling' },
      { c: '😒', n: 'Скучно', k: 'unamused' },
      { c: '😓', n: 'Холодный пот', k: 'sweat downcast' },
      { c: '😔', n: 'Грустный', k: 'pensive грусть' },
      { c: '😕', n: 'В замешательстве', k: 'confused' },
      { c: '🙁', n: 'Лёгкая грусть', k: 'slight frown' },
      { c: '☹️', n: 'Грустный', k: 'frowning' },
      { c: '😖', n: 'Терплю', k: 'confounded' },
      { c: '😞', n: 'Разочарован', k: 'disappointed' },
      { c: '😟', n: 'Беспокоюсь', k: 'worried' },
      { c: '😢', n: 'Плачу', k: 'cry слеза' },
      { c: '😭', n: 'Рыдаю', k: 'loudly crying' },
      { c: '😤', n: 'Пыхтит', k: 'triumph' },
      { c: '😠', n: 'Сердится', k: 'angry' },
      { c: '😡', n: 'Очень злой', k: 'pouting rage' },
      { c: '🤬', n: 'Ругается', k: 'swearing cursing' },
      { c: '😈', n: 'Чертёнок', k: 'smiling imp devil' },
      { c: '👿', n: 'Злой чёрт', k: 'imp angry devil' },
      { c: '💀', n: 'Череп', k: 'skull death' },
      { c: '☠️', n: 'Череп и кости', k: 'skull crossbones' },
      { c: '💩', n: 'Какашка', k: 'poo poop' },
      { c: '🤡', n: 'Клоун', k: 'clown' },
      { c: '👻', n: 'Привидение', k: 'ghost' },
      { c: '👽', n: 'Пришелец', k: 'alien' },
      { c: '🤖', n: 'Робот', k: 'robot' },
      { c: '🎃', n: 'Тыква', k: 'pumpkin halloween' },
      { c: '😺', n: 'Кот улыбается', k: 'smiling cat' },
      { c: '😸', n: 'Кот смеётся', k: 'grinning cat' },
      { c: '😹', n: 'Кот плачет', k: 'cat tears joy' },
      { c: '😻', n: 'Кот влюблён', k: 'heart eyes cat' },
      { c: '😼', n: 'Кот хитрый', k: 'wry cat' },
      { c: '😽', n: 'Кот целует', k: 'kissing cat' },
      { c: '🙀', n: 'Кот в шоке', k: 'weary cat' },
      { c: '😿', n: 'Кот грустит', k: 'crying cat' },
      { c: '😾', n: 'Кот злится', k: 'pouting cat' },
      { c: '❤️', n: 'Сердце', k: 'heart любовь' },
      { c: '🧡', n: 'Оранжевое сердце', k: 'orange heart' },
      { c: '💛', n: 'Жёлтое сердце', k: 'yellow heart' },
      { c: '💚', n: 'Зелёное сердце', k: 'green heart' },
      { c: '💙', n: 'Синее сердце', k: 'blue heart' },
      { c: '💜', n: 'Фиолетовое сердце', k: 'purple heart' },
      { c: '🖤', n: 'Чёрное сердце', k: 'black heart' },
      { c: '🤍', n: 'Белое сердце', k: 'white heart' },
      { c: '🤎', n: 'Коричневое сердце', k: 'brown heart' },
      { c: '💔', n: 'Разбитое сердце', k: 'broken heart' },
      { c: '💕', n: 'Два сердца', k: 'two hearts' },
      { c: '💖', n: 'Сверкающее сердце', k: 'sparkling heart' },
      { c: '💗', n: 'Растущее сердце', k: 'growing heart' },
      { c: '💘', n: 'Сердце со стрелой', k: 'heart arrow' },
      { c: '💝', n: 'Сердце с лентой', k: 'heart ribbon gift' },
      { c: '💞', n: 'Кружение сердец', k: 'revolving hearts' },
      { c: '💟', n: 'Сердце-украшение', k: 'heart decoration' },
    ],
  },
  {
    id: 'people',
    title: 'Люди и тело',
    icon: '🧑',
    items: [
      { c: '👋', n: 'Привет', k: 'wave hello hi' },
      { c: '🤚', n: 'Поднятая рука', k: 'raised hand back' },
      { c: '🖐️', n: 'Растопыренная рука', k: 'hand fingers splayed' },
      { c: '✋', n: 'Стой', k: 'stop hand' },
      { c: '🖖', n: 'Спок', k: 'vulcan salute' },
      { c: '👌', n: 'Окей', k: 'ok hand' },
      { c: '🤌', n: 'Сложенные пальцы', k: 'pinched fingers' },
      { c: '🤏', n: 'Чуть-чуть', k: 'pinching' },
      { c: '✌️', n: 'Победа', k: 'victory peace' },
      { c: '🤞', n: 'Скрещенные пальцы', k: 'crossed fingers' },
      { c: '🤟', n: 'Я тебя люблю', k: 'love you gesture' },
      { c: '🤘', n: 'Рога', k: 'horns rock' },
      { c: '🤙', n: 'Звони', k: 'call me hand' },
      { c: '👈', n: 'Палец влево', k: 'point left' },
      { c: '👉', n: 'Палец вправо', k: 'point right' },
      { c: '👆', n: 'Палец вверх', k: 'point up' },
      { c: '🖕', n: 'Средний палец', k: 'middle finger' },
      { c: '👇', n: 'Палец вниз', k: 'point down' },
      { c: '☝️', n: 'Указ. палец вверх', k: 'index up' },
      { c: '👍', n: 'Класс', k: 'thumbs up like' },
      { c: '👎', n: 'Не нравится', k: 'thumbs down' },
      { c: '✊', n: 'Кулак', k: 'fist raised' },
      { c: '👊', n: 'Удар', k: 'fist punch' },
      { c: '🤛', n: 'Кулак влево', k: 'left fist' },
      { c: '🤜', n: 'Кулак вправо', k: 'right fist' },
      { c: '👏', n: 'Аплодисменты', k: 'clap applause' },
      { c: '🙌', n: 'Хвала', k: 'raised hands' },
      { c: '👐', n: 'Открытые руки', k: 'open hands' },
      { c: '🤲', n: 'Ладони вверх', k: 'palms up' },
      { c: '🤝', n: 'Рукопожатие', k: 'handshake' },
      { c: '🙏', n: 'Молитва', k: 'praying thanks please' },
      { c: '💪', n: 'Мышцы', k: 'flex biceps' },
      { c: '🦾', n: 'Механ. рука', k: 'mechanical arm' },
      { c: '🦿', n: 'Механ. нога', k: 'mechanical leg' },
      { c: '🦵', n: 'Нога', k: 'leg' },
      { c: '🦶', n: 'Стопа', k: 'foot' },
      { c: '👂', n: 'Ухо', k: 'ear' },
      { c: '🦻', n: 'Слуховой аппарат', k: 'hearing aid' },
      { c: '👃', n: 'Нос', k: 'nose' },
      { c: '🧠', n: 'Мозг', k: 'brain' },
      { c: '🫀', n: 'Анатом. сердце', k: 'anatomical heart' },
      { c: '🫁', n: 'Лёгкие', k: 'lungs' },
      { c: '🦷', n: 'Зуб', k: 'tooth' },
      { c: '🦴', n: 'Кость', k: 'bone' },
      { c: '👀', n: 'Глаза', k: 'eyes' },
      { c: '👁️', n: 'Глаз', k: 'eye' },
      { c: '👅', n: 'Язык', k: 'tongue' },
      { c: '👄', n: 'Губы', k: 'mouth lips' },
      { c: '👶', n: 'Малыш', k: 'baby' },
      { c: '🧒', n: 'Ребёнок', k: 'child' },
      { c: '👦', n: 'Мальчик', k: 'boy' },
      { c: '👧', n: 'Девочка', k: 'girl' },
      { c: '🧑', n: 'Человек', k: 'person adult' },
      { c: '👨', n: 'Мужчина', k: 'man' },
      { c: '👩', n: 'Женщина', k: 'woman' },
      { c: '🧓', n: 'Пожилой', k: 'older adult' },
      { c: '👴', n: 'Дедушка', k: 'old man' },
      { c: '👵', n: 'Бабушка', k: 'old woman' },
      { c: '👨‍💻', n: 'Программист', k: 'man technologist programmer' },
      { c: '👩‍💻', n: 'Программистка', k: 'woman technologist programmer' },
      { c: '👨‍💼', n: 'Офисный работник', k: 'man office worker' },
      { c: '👩‍💼', n: 'Офисная работница', k: 'woman office worker' },
      { c: '👨‍🔧', n: 'Механик', k: 'mechanic man' },
      { c: '👩‍🔧', n: 'Механик', k: 'mechanic woman' },
      { c: '👨‍🏫', n: 'Учитель', k: 'teacher man' },
      { c: '👩‍🏫', n: 'Учительница', k: 'teacher woman' },
      { c: '👨‍⚖️', n: 'Судья', k: 'judge man' },
      { c: '👩‍⚖️', n: 'Судья', k: 'judge woman' },
      { c: '👮', n: 'Полицейский', k: 'police officer' },
      { c: '🕵️', n: 'Детектив', k: 'detective spy' },
      { c: '👷', n: 'Строитель', k: 'construction worker' },
      { c: '🤴', n: 'Принц', k: 'prince' },
      { c: '👸', n: 'Принцесса', k: 'princess' },
      { c: '🧑‍🎓', n: 'Студент', k: 'student' },
      { c: '🧑‍🎤', n: 'Певец', k: 'singer' },
      { c: '🧑‍🍳', n: 'Повар', k: 'cook chef' },
      { c: '🤵', n: 'В смокинге', k: 'tuxedo' },
      { c: '👰', n: 'Невеста', k: 'bride veil' },
    ],
  },
  {
    id: 'nature',
    title: 'Природа и животные',
    icon: '🐻',
    items: [
      { c: '🐶', n: 'Собака', k: 'dog собака щенок' },
      { c: '🐱', n: 'Кошка', k: 'cat кот кошка' },
      { c: '🐭', n: 'Мышка', k: 'mouse' },
      { c: '🐹', n: 'Хомяк', k: 'hamster' },
      { c: '🐰', n: 'Кролик', k: 'rabbit заяц' },
      { c: '🦊', n: 'Лиса', k: 'fox лиса' },
      { c: '🐻', n: 'Медведь', k: 'bear медведь' },
      { c: '🐼', n: 'Панда', k: 'panda' },
      { c: '🐻‍❄️', n: 'Белый медведь', k: 'polar bear' },
      { c: '🐨', n: 'Коала', k: 'koala' },
      { c: '🐯', n: 'Тигр', k: 'tiger' },
      { c: '🦁', n: 'Лев', k: 'lion' },
      { c: '🐮', n: 'Корова', k: 'cow' },
      { c: '🐷', n: 'Свинья', k: 'pig свинья' },
      { c: '🐽', n: 'Пятачок', k: 'pig nose' },
      { c: '🐸', n: 'Лягушка', k: 'frog' },
      { c: '🐵', n: 'Обезьяна', k: 'monkey' },
      { c: '🙈', n: 'Не вижу', k: 'see no evil monkey' },
      { c: '🙉', n: 'Не слышу', k: 'hear no evil monkey' },
      { c: '🙊', n: 'Не скажу', k: 'speak no evil monkey' },
      { c: '🐒', n: 'Обезьяна', k: 'monkey 2' },
      { c: '🐔', n: 'Курица', k: 'chicken' },
      { c: '🐧', n: 'Пингвин', k: 'penguin' },
      { c: '🐦', n: 'Птица', k: 'bird' },
      { c: '🐤', n: 'Цыплёнок', k: 'baby chick' },
      { c: '🦆', n: 'Утка', k: 'duck' },
      { c: '🦅', n: 'Орёл', k: 'eagle' },
      { c: '🦉', n: 'Сова', k: 'owl' },
      { c: '🦇', n: 'Летучая мышь', k: 'bat' },
      { c: '🐺', n: 'Волк', k: 'wolf волк' },
      { c: '🐗', n: 'Кабан', k: 'boar' },
      { c: '🐴', n: 'Лошадь', k: 'horse' },
      { c: '🦄', n: 'Единорог', k: 'unicorn' },
      { c: '🐝', n: 'Пчела', k: 'bee пчела' },
      { c: '🐛', n: 'Гусеница', k: 'bug caterpillar' },
      { c: '🦋', n: 'Бабочка', k: 'butterfly' },
      { c: '🐌', n: 'Улитка', k: 'snail' },
      { c: '🐞', n: 'Божья коровка', k: 'lady beetle' },
      { c: '🐜', n: 'Муравей', k: 'ant' },
      { c: '🪰', n: 'Муха', k: 'fly' },
      { c: '🪲', n: 'Жук', k: 'beetle' },
      { c: '🦂', n: 'Скорпион', k: 'scorpion' },
      { c: '🐢', n: 'Черепаха', k: 'turtle' },
      { c: '🐍', n: 'Змея', k: 'snake' },
      { c: '🦎', n: 'Ящерица', k: 'lizard' },
      { c: '🦖', n: 'T-Rex', k: 'dinosaur t-rex' },
      { c: '🐙', n: 'Осьминог', k: 'octopus' },
      { c: '🦑', n: 'Кальмар', k: 'squid' },
      { c: '🦐', n: 'Креветка', k: 'shrimp' },
      { c: '🦞', n: 'Лобстер', k: 'lobster' },
      { c: '🦀', n: 'Краб', k: 'crab' },
      { c: '🐡', n: 'Рыба-шар', k: 'blowfish' },
      { c: '🐠', n: 'Рыбка', k: 'tropical fish' },
      { c: '🐟', n: 'Рыба', k: 'fish' },
      { c: '🐬', n: 'Дельфин', k: 'dolphin' },
      { c: '🐳', n: 'Кит', k: 'whale' },
      { c: '🦈', n: 'Акула', k: 'shark' },
      { c: '🐊', n: 'Крокодил', k: 'crocodile' },
      { c: '🦓', n: 'Зебра', k: 'zebra' },
      { c: '🦒', n: 'Жираф', k: 'giraffe' },
      { c: '🦔', n: 'Ёжик', k: 'hedgehog' },
      { c: '🦦', n: 'Выдра', k: 'otter' },
      { c: '🦥', n: 'Ленивец', k: 'sloth' },
      { c: '🐘', n: 'Слон', k: 'elephant' },
      { c: '🦏', n: 'Носорог', k: 'rhinoceros' },
      { c: '🦛', n: 'Бегемот', k: 'hippopotamus' },
      { c: '🐪', n: 'Верблюд', k: 'camel' },
      { c: '🐫', n: 'Двугорбый верблюд', k: 'bactrian camel' },
      { c: '🦘', n: 'Кенгуру', k: 'kangaroo' },
      { c: '🦬', n: 'Бизон', k: 'bison' },
      { c: '🐂', n: 'Бык', k: 'ox bull' },
      { c: '🐃', n: 'Буйвол', k: 'water buffalo' },
      { c: '🐄', n: 'Корова', k: 'cow body' },
      { c: '🐎', n: 'Лошадь', k: 'horse body' },
      { c: '🐖', n: 'Свинья', k: 'pig body' },
      { c: '🐏', n: 'Баран', k: 'ram' },
      { c: '🐑', n: 'Овца', k: 'sheep' },
      { c: '🐐', n: 'Коза', k: 'goat' },
      { c: '🦌', n: 'Олень', k: 'deer' },
      { c: '🐕', n: 'Собака', k: 'dog 2' },
      { c: '🐩', n: 'Пудель', k: 'poodle' },
      { c: '🦮', n: 'Поводырь', k: 'guide dog' },
      { c: '🐕‍🦺', n: 'Служебная собака', k: 'service dog' },
      { c: '🐈', n: 'Кошка', k: 'cat 2' },
      { c: '🪶', n: 'Перо', k: 'feather' },
      { c: '🐓', n: 'Петух', k: 'rooster' },
      { c: '🦃', n: 'Индейка', k: 'turkey' },
      { c: '🦚', n: 'Павлин', k: 'peacock' },
      { c: '🦜', n: 'Попугай', k: 'parrot' },
      { c: '🦢', n: 'Лебедь', k: 'swan' },
      { c: '🌵', n: 'Кактус', k: 'cactus' },
      { c: '🎄', n: 'Ёлка', k: 'christmas tree' },
      { c: '🌲', n: 'Сосна', k: 'evergreen tree' },
      { c: '🌳', n: 'Дерево', k: 'tree' },
      { c: '🌴', n: 'Пальма', k: 'palm tree' },
      { c: '🪴', n: 'Растение', k: 'potted plant' },
      { c: '🌱', n: 'Росток', k: 'seedling' },
      { c: '🌿', n: 'Зелень', k: 'herb' },
      { c: '☘️', n: 'Трилистник', k: 'shamrock' },
      { c: '🍀', n: 'Клевер', k: 'four leaf clover' },
      { c: '🍃', n: 'Лист на ветру', k: 'leaf wind' },
      { c: '🍂', n: 'Опавшие листья', k: 'fallen leaves' },
      { c: '🍁', n: 'Кленовый лист', k: 'maple leaf' },
      { c: '🍄', n: 'Гриб', k: 'mushroom' },
      { c: '🌾', n: 'Колос', k: 'sheaf of rice' },
      { c: '💐', n: 'Букет', k: 'bouquet' },
      { c: '🌹', n: 'Роза', k: 'rose' },
      { c: '🌷', n: 'Тюльпан', k: 'tulip' },
      { c: '🌻', n: 'Подсолнух', k: 'sunflower' },
      { c: '🌼', n: 'Цветок', k: 'blossom' },
      { c: '🌸', n: 'Сакура', k: 'cherry blossom' },
      { c: '🌺', n: 'Гибискус', k: 'hibiscus' },
      { c: '🪷', n: 'Лотос', k: 'lotus' },
      { c: '🌞', n: 'Солнце', k: 'sun with face' },
      { c: '🌝', n: 'Луна', k: 'full moon face' },
      { c: '🌚', n: 'Новолуние', k: 'new moon face' },
      { c: '🌙', n: 'Месяц', k: 'crescent moon' },
      { c: '⭐', n: 'Звезда', k: 'star' },
      { c: '🌟', n: 'Сияющая звезда', k: 'glowing star' },
      { c: '✨', n: 'Сверкание', k: 'sparkles' },
      { c: '⚡', n: 'Молния', k: 'high voltage' },
      { c: '☄️', n: 'Комета', k: 'comet' },
      { c: '💥', n: 'Взрыв', k: 'collision' },
      { c: '🔥', n: 'Огонь', k: 'fire' },
      { c: '🌪️', n: 'Торнадо', k: 'tornado' },
      { c: '🌈', n: 'Радуга', k: 'rainbow' },
      { c: '☀️', n: 'Солнце', k: 'sun' },
      { c: '⛅', n: 'Солнце за облаком', k: 'sun behind cloud' },
      { c: '☁️', n: 'Облако', k: 'cloud' },
      { c: '🌧️', n: 'Дождь', k: 'rain cloud' },
      { c: '⛈️', n: 'Гроза', k: 'storm' },
      { c: '🌩️', n: 'Молния', k: 'lightning cloud' },
      { c: '🌨️', n: 'Снег', k: 'snow cloud' },
      { c: '❄️', n: 'Снежинка', k: 'snowflake' },
      { c: '☃️', n: 'Снеговик', k: 'snowman' },
      { c: '🌊', n: 'Волна', k: 'wave water' },
      { c: '💧', n: 'Капля', k: 'droplet' },
    ],
  },
  {
    id: 'food',
    title: 'Еда и напитки',
    icon: '🍕',
    items: [
      { c: '🍏', n: 'Зелёное яблоко', k: 'green apple' },
      { c: '🍎', n: 'Красное яблоко', k: 'red apple' },
      { c: '🍐', n: 'Груша', k: 'pear' },
      { c: '🍊', n: 'Апельсин', k: 'tangerine orange' },
      { c: '🍋', n: 'Лимон', k: 'lemon' },
      { c: '🍌', n: 'Банан', k: 'banana' },
      { c: '🍉', n: 'Арбуз', k: 'watermelon' },
      { c: '🍇', n: 'Виноград', k: 'grapes' },
      { c: '🍓', n: 'Клубника', k: 'strawberry' },
      { c: '🫐', n: 'Черника', k: 'blueberries' },
      { c: '🍈', n: 'Дыня', k: 'melon' },
      { c: '🍒', n: 'Вишня', k: 'cherries' },
      { c: '🍑', n: 'Персик', k: 'peach' },
      { c: '🥭', n: 'Манго', k: 'mango' },
      { c: '🍍', n: 'Ананас', k: 'pineapple' },
      { c: '🥥', n: 'Кокос', k: 'coconut' },
      { c: '🥝', n: 'Киви', k: 'kiwi' },
      { c: '🍅', n: 'Помидор', k: 'tomato' },
      { c: '🍆', n: 'Баклажан', k: 'eggplant' },
      { c: '🥑', n: 'Авокадо', k: 'avocado' },
      { c: '🥦', n: 'Брокколи', k: 'broccoli' },
      { c: '🥬', n: 'Салат', k: 'leafy green' },
      { c: '🥒', n: 'Огурец', k: 'cucumber' },
      { c: '🌶️', n: 'Острый перец', k: 'hot pepper' },
      { c: '🫑', n: 'Сладкий перец', k: 'bell pepper' },
      { c: '🌽', n: 'Кукуруза', k: 'corn' },
      { c: '🥕', n: 'Морковь', k: 'carrot' },
      { c: '🧄', n: 'Чеснок', k: 'garlic' },
      { c: '🧅', n: 'Лук', k: 'onion' },
      { c: '🥔', n: 'Картошка', k: 'potato' },
      { c: '🍠', n: 'Сладкий картофель', k: 'sweet potato' },
      { c: '🥯', n: 'Бейгл', k: 'bagel' },
      { c: '🥖', n: 'Багет', k: 'baguette' },
      { c: '🍞', n: 'Хлеб', k: 'bread' },
      { c: '🥐', n: 'Круассан', k: 'croissant' },
      { c: '🥨', n: 'Крендель', k: 'pretzel' },
      { c: '🧀', n: 'Сыр', k: 'cheese' },
      { c: '🥚', n: 'Яйцо', k: 'egg' },
      { c: '🍳', n: 'Яичница', k: 'cooking' },
      { c: '🥓', n: 'Бекон', k: 'bacon' },
      { c: '🥩', n: 'Стейк', k: 'cut of meat' },
      { c: '🍗', n: 'Куриная ножка', k: 'poultry leg' },
      { c: '🍖', n: 'Мясо', k: 'meat on bone' },
      { c: '🌭', n: 'Хот-дог', k: 'hot dog' },
      { c: '🍔', n: 'Бургер', k: 'hamburger' },
      { c: '🍟', n: 'Картошка фри', k: 'french fries' },
      { c: '🍕', n: 'Пицца', k: 'pizza' },
      { c: '🥪', n: 'Сэндвич', k: 'sandwich' },
      { c: '🌮', n: 'Тако', k: 'taco' },
      { c: '🌯', n: 'Буррито', k: 'burrito' },
      { c: '🫔', n: 'Тамале', k: 'tamale' },
      { c: '🥙', n: 'Шаурма', k: 'stuffed flatbread' },
      { c: '🧆', n: 'Фалафель', k: 'falafel' },
      { c: '🥗', n: 'Салат', k: 'green salad' },
      { c: '🥘', n: 'Сковорода', k: 'shallow pan' },
      { c: '🍲', n: 'Рагу', k: 'pot of food' },
      { c: '🫕', n: 'Фондю', k: 'fondue' },
      { c: '🥣', n: 'Миска', k: 'bowl spoon' },
      { c: '🍝', n: 'Спагетти', k: 'spaghetti' },
      { c: '🍜', n: 'Лапша', k: 'noodles ramen' },
      { c: '🍣', n: 'Суши', k: 'sushi' },
      { c: '🍱', n: 'Бенто', k: 'bento' },
      { c: '🥟', n: 'Пельмени', k: 'dumpling' },
      { c: '🍤', n: 'Креветка темпура', k: 'fried shrimp' },
      { c: '🍙', n: 'Онигири', k: 'rice ball' },
      { c: '🍚', n: 'Рис', k: 'cooked rice' },
      { c: '🍘', n: 'Сэмбэй', k: 'rice cracker' },
      { c: '🍢', n: 'Оденчи', k: 'oden' },
      { c: '🍡', n: 'Данго', k: 'dango' },
      { c: '🍧', n: 'Сахарная вата', k: 'shaved ice' },
      { c: '🍨', n: 'Мороженое', k: 'ice cream' },
      { c: '🍦', n: 'Рожок', k: 'soft ice cream' },
      { c: '🥧', n: 'Пирог', k: 'pie' },
      { c: '🧁', n: 'Капкейк', k: 'cupcake' },
      { c: '🍰', n: 'Кусок торта', k: 'shortcake' },
      { c: '🎂', n: 'Торт', k: 'birthday cake' },
      { c: '🍮', n: 'Флан', k: 'flan custard' },
      { c: '🍭', n: 'Леденец', k: 'lollipop' },
      { c: '🍬', n: 'Конфета', k: 'candy' },
      { c: '🍫', n: 'Шоколад', k: 'chocolate bar' },
      { c: '🍿', n: 'Попкорн', k: 'popcorn' },
      { c: '🍩', n: 'Пончик', k: 'doughnut' },
      { c: '🍪', n: 'Печенье', k: 'cookie' },
      { c: '🌰', n: 'Каштан', k: 'chestnut' },
      { c: '🥜', n: 'Орехи', k: 'peanuts' },
      { c: '🍯', n: 'Мёд', k: 'honey pot' },
      { c: '🥛', n: 'Молоко', k: 'milk' },
      { c: '🍼', n: 'Бутылочка', k: 'baby bottle' },
      { c: '☕', n: 'Кофе', k: 'hot coffee' },
      { c: '🫖', n: 'Чайник', k: 'teapot' },
      { c: '🍵', n: 'Чай', k: 'tea' },
      { c: '🧃', n: 'Сок в коробке', k: 'beverage box' },
      { c: '🥤', n: 'Стакан с трубочкой', k: 'cup straw' },
      { c: '🧋', n: 'Bubble tea', k: 'bubble tea' },
      { c: '🍶', n: 'Саке', k: 'sake' },
      { c: '🍺', n: 'Пиво', k: 'beer mug' },
      { c: '🍻', n: 'Чокаемся пивом', k: 'clinking beers' },
      { c: '🥂', n: 'Шампанское', k: 'clinking glasses' },
      { c: '🍷', n: 'Вино', k: 'wine glass' },
      { c: '🥃', n: 'Виски', k: 'tumbler glass whisky' },
      { c: '🍸', n: 'Коктейль', k: 'cocktail glass' },
      { c: '🍹', n: 'Тропический коктейль', k: 'tropical drink' },
      { c: '🍾', n: 'Шампанское бутылка', k: 'bottle with cork' },
      { c: '🧉', n: 'Мате', k: 'mate' },
      { c: '🧊', n: 'Лёд', k: 'ice cube' },
      { c: '🥄', n: 'Ложка', k: 'spoon' },
      { c: '🍴', n: 'Приборы', k: 'fork knife' },
      { c: '🍽️', n: 'Тарелка', k: 'fork knife plate' },
      { c: '🥢', n: 'Палочки', k: 'chopsticks' },
      { c: '🧂', n: 'Соль', k: 'salt' },
    ],
  },
  {
    id: 'activities',
    title: 'Активности',
    icon: '⚽',
    items: [
      { c: '⚽', n: 'Футбольный мяч', k: 'soccer ball' },
      { c: '🏀', n: 'Баскетбольный мяч', k: 'basketball' },
      { c: '🏈', n: 'Американский футбол', k: 'american football' },
      { c: '⚾', n: 'Бейсбол', k: 'baseball' },
      { c: '🥎', n: 'Софтбол', k: 'softball' },
      { c: '🎾', n: 'Теннис', k: 'tennis' },
      { c: '🏐', n: 'Волейбол', k: 'volleyball' },
      { c: '🏉', n: 'Регби', k: 'rugby football' },
      { c: '🎱', n: 'Бильярд', k: 'pool 8 ball' },
      { c: '🪀', n: 'Йо-йо', k: 'yo-yo' },
      { c: '🏓', n: 'Пинг-понг', k: 'ping pong' },
      { c: '🏸', n: 'Бадминтон', k: 'badminton' },
      { c: '🥊', n: 'Боксёрская перчатка', k: 'boxing glove' },
      { c: '🥋', n: 'Кимоно', k: 'martial arts uniform' },
      { c: '⛳', n: 'Гольф', k: 'flag in hole golf' },
      { c: '⛸️', n: 'Коньки', k: 'ice skate' },
      { c: '🎣', n: 'Удочка', k: 'fishing pole' },
      { c: '🎽', n: 'Майка', k: 'running shirt' },
      { c: '🎿', n: 'Лыжи', k: 'skis' },
      { c: '🛷', n: 'Сани', k: 'sled' },
      { c: '🥌', n: 'Кёрлинг', k: 'curling stone' },
      { c: '🎯', n: 'Мишень', k: 'direct hit target' },
      { c: '🪁', n: 'Воздушный змей', k: 'kite' },
      { c: '🏹', n: 'Лук и стрела', k: 'bow and arrow' },
      { c: '🎣', n: 'Рыбалка', k: 'fishing' },
      { c: '🥅', n: 'Ворота', k: 'goal net' },
      { c: '🎱', n: 'Шар', k: 'billiard' },
      { c: '🔮', n: 'Магический шар', k: 'crystal ball' },
      { c: '🪄', n: 'Волшебная палочка', k: 'magic wand' },
      { c: '🎮', n: 'Геймпад', k: 'video game' },
      { c: '🕹️', n: 'Джойстик', k: 'joystick' },
      { c: '🎰', n: 'Слот-машина', k: 'slot machine' },
      { c: '🎲', n: 'Кубик', k: 'game die' },
      { c: '🧩', n: 'Пазл', k: 'puzzle piece' },
      { c: '♟️', n: 'Шахматная пешка', k: 'chess pawn' },
      { c: '🎭', n: 'Маски', k: 'performing arts' },
      { c: '🎨', n: 'Палитра', k: 'artist palette' },
      { c: '🧵', n: 'Нитки', k: 'thread spool' },
      { c: '🪡', n: 'Иголка', k: 'sewing needle' },
      { c: '🧶', n: 'Клубок', k: 'yarn' },
      { c: '🪢', n: 'Узел', k: 'knot' },
      { c: '🎤', n: 'Микрофон', k: 'microphone' },
      { c: '🎧', n: 'Наушники', k: 'headphones' },
      { c: '🎼', n: 'Партитура', k: 'musical score' },
      { c: '🎹', n: 'Пианино', k: 'piano' },
      { c: '🥁', n: 'Барабан', k: 'drum' },
      { c: '🪘', n: 'Длинный барабан', k: 'long drum' },
      { c: '🎷', n: 'Саксофон', k: 'saxophone' },
      { c: '🎺', n: 'Труба', k: 'trumpet' },
      { c: '🎸', n: 'Гитара', k: 'guitar' },
      { c: '🪕', n: 'Банджо', k: 'banjo' },
      { c: '🎻', n: 'Скрипка', k: 'violin' },
      { c: '🎬', n: 'Хлопушка', k: 'clapper board film' },
      { c: '🏆', n: 'Кубок', k: 'trophy' },
      { c: '🥇', n: 'Золотая медаль', k: 'gold medal first' },
      { c: '🥈', n: 'Серебряная медаль', k: 'silver medal second' },
      { c: '🥉', n: 'Бронзовая медаль', k: 'bronze medal third' },
      { c: '🏅', n: 'Спортивная медаль', k: 'sports medal' },
      { c: '🎖️', n: 'Военная медаль', k: 'military medal' },
      { c: '🎗️', n: 'Лента', k: 'reminder ribbon' },
      { c: '🎫', n: 'Билет', k: 'ticket' },
      { c: '🎟️', n: 'Билет с кодом', k: 'admission ticket' },
      { c: '🎪', n: 'Цирк', k: 'circus tent' },
      { c: '🎢', n: 'Американские горки', k: 'roller coaster' },
      { c: '🎡', n: 'Колесо обозрения', k: 'ferris wheel' },
      { c: '🎠', n: 'Карусель', k: 'carousel horse' },
      { c: '🎉', n: 'Хлопушка', k: 'party popper' },
      { c: '🎊', n: 'Конфетти', k: 'confetti ball' },
      { c: '🎈', n: 'Шарик', k: 'balloon' },
      { c: '🎁', n: 'Подарок', k: 'wrapped gift' },
      { c: '🎀', n: 'Бант', k: 'ribbon bow' },
      { c: '🎇', n: 'Бенгальский огонь', k: 'sparkler' },
      { c: '🎆', n: 'Фейерверк', k: 'fireworks' },
      { c: '🪅', n: 'Пиньята', k: 'piñata' },
      { c: '🪩', n: 'Диско-шар', k: 'mirror ball disco' },
    ],
  },
  {
    id: 'travel',
    title: 'Путешествия и места',
    icon: '🌍',
    items: [
      { c: '🚗', n: 'Машина', k: 'car automobile' },
      { c: '🚕', n: 'Такси', k: 'taxi' },
      { c: '🚙', n: 'Внедорожник', k: 'suv' },
      { c: '🚌', n: 'Автобус', k: 'bus' },
      { c: '🚎', n: 'Троллейбус', k: 'trolleybus' },
      { c: '🏎️', n: 'Гоночная машина', k: 'racing car' },
      { c: '🚓', n: 'Полицейская машина', k: 'police car' },
      { c: '🚑', n: 'Скорая', k: 'ambulance' },
      { c: '🚒', n: 'Пожарная', k: 'fire engine' },
      { c: '🚐', n: 'Минивэн', k: 'minibus' },
      { c: '🛻', n: 'Пикап', k: 'pickup truck' },
      { c: '🚚', n: 'Грузовик', k: 'delivery truck' },
      { c: '🚛', n: 'Фура', k: 'articulated lorry' },
      { c: '🚜', n: 'Трактор', k: 'tractor' },
      { c: '🦯', n: 'Белая трость', k: 'white cane' },
      { c: '🦽', n: 'Инвалидная коляска', k: 'manual wheelchair' },
      { c: '🛵', n: 'Скутер', k: 'motor scooter' },
      { c: '🏍️', n: 'Мотоцикл', k: 'motorcycle' },
      { c: '🛺', n: 'Тук-тук', k: 'auto rickshaw' },
      { c: '🚲', n: 'Велосипед', k: 'bicycle' },
      { c: '🛴', n: 'Самокат', k: 'kick scooter' },
      { c: '🛹', n: 'Скейтборд', k: 'skateboard' },
      { c: '🛼', n: 'Ролики', k: 'roller skate' },
      { c: '🚏', n: 'Автобусная остановка', k: 'bus stop' },
      { c: '🛣️', n: 'Шоссе', k: 'motorway' },
      { c: '🛤️', n: 'Железная дорога', k: 'railway track' },
      { c: '🛢️', n: 'Бочка нефти', k: 'oil drum' },
      { c: '⛽', n: 'Заправка', k: 'fuel pump' },
      { c: '🚨', n: 'Полицейская мигалка', k: 'police light' },
      { c: '🚥', n: 'Горизонтальный светофор', k: 'horizontal traffic light' },
      { c: '🚦', n: 'Светофор', k: 'vertical traffic light' },
      { c: '🛑', n: 'Стоп', k: 'stop sign' },
      { c: '🚧', n: 'Дорожные работы', k: 'construction sign' },
      { c: '⚓', n: 'Якорь', k: 'anchor' },
      { c: '⛵', n: 'Парусник', k: 'sailboat' },
      { c: '🛶', n: 'Каноэ', k: 'canoe' },
      { c: '🚤', n: 'Катер', k: 'speedboat' },
      { c: '🛳️', n: 'Круизный лайнер', k: 'passenger ship' },
      { c: '⛴️', n: 'Паром', k: 'ferry' },
      { c: '🛥️', n: 'Моторная лодка', k: 'motor boat' },
      { c: '🚢', n: 'Корабль', k: 'ship' },
      { c: '✈️', n: 'Самолёт', k: 'airplane' },
      { c: '🛩️', n: 'Малый самолёт', k: 'small airplane' },
      { c: '🛫', n: 'Взлёт', k: 'airplane departure' },
      { c: '🛬', n: 'Посадка', k: 'airplane arrival' },
      { c: '🪂', n: 'Парашют', k: 'parachute' },
      { c: '💺', n: 'Кресло', k: 'seat' },
      { c: '🚁', n: 'Вертолёт', k: 'helicopter' },
      { c: '🚟', n: 'Подвесная дорога', k: 'suspension railway' },
      { c: '🚠', n: 'Канатная дорога', k: 'mountain cableway' },
      { c: '🚡', n: 'Воздушный трамвай', k: 'aerial tramway' },
      { c: '🛰️', n: 'Спутник', k: 'satellite' },
      { c: '🚀', n: 'Ракета', k: 'rocket' },
      { c: '🛸', n: 'НЛО', k: 'flying saucer ufo' },
      { c: '🛎️', n: 'Колокольчик ресепшен', k: 'bellhop bell' },
      { c: '🧳', n: 'Чемодан', k: 'luggage' },
      { c: '⌛', n: 'Песочные часы', k: 'hourglass done' },
      { c: '⏳', n: 'Часы с песком', k: 'hourglass not done' },
      { c: '⌚', n: 'Часы', k: 'watch' },
      { c: '⏰', n: 'Будильник', k: 'alarm clock' },
      { c: '⏱️', n: 'Секундомер', k: 'stopwatch' },
      { c: '⏲️', n: 'Таймер', k: 'timer clock' },
      { c: '🕰️', n: 'Каминные часы', k: 'mantelpiece clock' },
      { c: '🌍', n: 'Земля Европа', k: 'earth africa europe globe' },
      { c: '🌎', n: 'Земля Америка', k: 'earth americas globe' },
      { c: '🌏', n: 'Земля Азия', k: 'earth asia globe' },
      { c: '🌐', n: 'Глобус', k: 'globe with meridians' },
      { c: '🗺️', n: 'Карта мира', k: 'world map' },
      { c: '🗾', n: 'Карта Японии', k: 'map of japan' },
      { c: '🏔️', n: 'Горы', k: 'snow capped mountain' },
      { c: '⛰️', n: 'Гора', k: 'mountain' },
      { c: '🌋', n: 'Вулкан', k: 'volcano' },
      { c: '🗻', n: 'Фудзи', k: 'mount fuji' },
      { c: '🏕️', n: 'Кемпинг', k: 'camping' },
      { c: '🏖️', n: 'Пляж', k: 'beach with umbrella' },
      { c: '🏜️', n: 'Пустыня', k: 'desert' },
      { c: '🏝️', n: 'Остров', k: 'desert island' },
      { c: '🏞️', n: 'Парк', k: 'national park' },
      { c: '🏟️', n: 'Стадион', k: 'stadium' },
      { c: '🏛️', n: 'Классическое здание', k: 'classical building' },
      { c: '🏗️', n: 'Стройка', k: 'building construction' },
      { c: '🧱', n: 'Кирпич', k: 'brick' },
      { c: '🪨', n: 'Камень', k: 'rock' },
      { c: '🪵', n: 'Бревно', k: 'wood log' },
      { c: '🛖', n: 'Хижина', k: 'hut' },
      { c: '🏘️', n: 'Дома', k: 'houses' },
      { c: '🏚️', n: 'Заброшенный дом', k: 'derelict house' },
      { c: '🏠', n: 'Дом', k: 'house' },
      { c: '🏡', n: 'Дом с садом', k: 'house with garden' },
      { c: '🏢', n: 'Офисное здание', k: 'office building' },
      { c: '🏣', n: 'Японская почта', k: 'japanese post office' },
      { c: '🏤', n: 'Почта', k: 'post office' },
      { c: '🏥', n: 'Больница', k: 'hospital' },
      { c: '🏦', n: 'Банк', k: 'bank' },
      { c: '🏨', n: 'Отель', k: 'hotel' },
      { c: '🏪', n: 'Магазин', k: 'convenience store' },
      { c: '🏫', n: 'Школа', k: 'school' },
      { c: '🏬', n: 'Универмаг', k: 'department store' },
      { c: '🏭', n: 'Фабрика', k: 'factory' },
      { c: '🏯', n: 'Японский замок', k: 'japanese castle' },
      { c: '🏰', n: 'Замок', k: 'castle' },
      { c: '💒', n: 'Свадьба', k: 'wedding' },
      { c: '🗼', n: 'Токийская башня', k: 'tokyo tower' },
      { c: '🗽', n: 'Статуя свободы', k: 'statue of liberty' },
      { c: '⛪', n: 'Церковь', k: 'church' },
      { c: '🕌', n: 'Мечеть', k: 'mosque' },
      { c: '🛕', n: 'Индуистский храм', k: 'hindu temple' },
      { c: '🕍', n: 'Синагога', k: 'synagogue' },
      { c: '⛩️', n: 'Тории', k: 'shinto shrine' },
      { c: '🕋', n: 'Кааба', k: 'kaaba' },
      { c: '⛲', n: 'Фонтан', k: 'fountain' },
      { c: '⛺', n: 'Палатка', k: 'tent' },
      { c: '🌁', n: 'Туман', k: 'foggy' },
      { c: '🌃', n: 'Звёздная ночь', k: 'night stars' },
      { c: '🏙️', n: 'Город', k: 'cityscape' },
      { c: '🌄', n: 'Восход над горами', k: 'sunrise over mountains' },
      { c: '🌅', n: 'Восход', k: 'sunrise' },
      { c: '🌆', n: 'Закат', k: 'cityscape at dusk' },
      { c: '🌇', n: 'Закат города', k: 'sunset' },
      { c: '🌉', n: 'Мост ночью', k: 'bridge at night' },
      { c: '♨️', n: 'Горячие источники', k: 'hot springs' },
      { c: '🎠', n: 'Карусель', k: 'carousel' },
      { c: '🎡', n: 'Чёртово колесо', k: 'ferris' },
      { c: '🎢', n: 'Горки', k: 'roller' },
      { c: '💈', n: 'Парикмахерская', k: 'barber pole' },
      { c: '🎪', n: 'Шапито', k: 'circus' },
    ],
  },
  {
    id: 'objects',
    title: 'Объекты',
    icon: '💡',
    items: [
      { c: '⌚', n: 'Часы', k: 'watch' },
      { c: '📱', n: 'Телефон', k: 'mobile phone' },
      { c: '📲', n: 'Звонок', k: 'mobile phone with arrow' },
      { c: '💻', n: 'Ноутбук', k: 'laptop computer' },
      { c: '⌨️', n: 'Клавиатура', k: 'keyboard' },
      { c: '🖥️', n: 'Компьютер', k: 'desktop computer' },
      { c: '🖨️', n: 'Принтер', k: 'printer' },
      { c: '🖱️', n: 'Мышка', k: 'computer mouse' },
      { c: '🖲️', n: 'Трекбол', k: 'trackball' },
      { c: '🕹️', n: 'Джойстик', k: 'joystick' },
      { c: '🗜️', n: 'Тиски', k: 'clamp' },
      { c: '💽', n: 'Минидиск', k: 'minidisc' },
      { c: '💾', n: 'Дискета', k: 'floppy disk' },
      { c: '💿', n: 'CD', k: 'optical disk cd' },
      { c: '📀', n: 'DVD', k: 'dvd' },
      { c: '📼', n: 'VHS', k: 'videocassette vhs' },
      { c: '📷', n: 'Фотоаппарат', k: 'camera' },
      { c: '📸', n: 'Фото со вспышкой', k: 'camera with flash' },
      { c: '📹', n: 'Видеокамера', k: 'video camera' },
      { c: '🎥', n: 'Кинокамера', k: 'movie camera' },
      { c: '📽️', n: 'Проектор', k: 'film projector' },
      { c: '🎞️', n: 'Плёнка', k: 'film frames' },
      { c: '📞', n: 'Трубка', k: 'telephone receiver' },
      { c: '☎️', n: 'Телефон', k: 'telephone' },
      { c: '📟', n: 'Пейджер', k: 'pager' },
      { c: '📠', n: 'Факс', k: 'fax' },
      { c: '📺', n: 'Телевизор', k: 'television' },
      { c: '📻', n: 'Радио', k: 'radio' },
      { c: '🎙️', n: 'Студийный микрофон', k: 'studio microphone' },
      { c: '🎚️', n: 'Слайдер', k: 'level slider' },
      { c: '🎛️', n: 'Ручки управления', k: 'control knobs' },
      { c: '🧭', n: 'Компас', k: 'compass' },
      { c: '⏱️', n: 'Секундомер', k: 'stopwatch' },
      { c: '🔋', n: 'Батарейка', k: 'battery' },
      { c: '🪫', n: 'Разряжена', k: 'low battery' },
      { c: '🔌', n: 'Вилка', k: 'electric plug' },
      { c: '💡', n: 'Лампочка', k: 'light bulb idea' },
      { c: '🔦', n: 'Фонарик', k: 'flashlight' },
      { c: '🕯️', n: 'Свеча', k: 'candle' },
      { c: '🪔', n: 'Глиняный светильник', k: 'diya lamp' },
      { c: '🧯', n: 'Огнетушитель', k: 'fire extinguisher' },
      { c: '🛢️', n: 'Бочка', k: 'oil drum' },
      { c: '💸', n: 'Деньги с крыльями', k: 'money with wings' },
      { c: '💵', n: 'Доллары', k: 'dollar banknote' },
      { c: '💴', n: 'Иены', k: 'yen banknote' },
      { c: '💶', n: 'Евро', k: 'euro banknote' },
      { c: '💷', n: 'Фунты', k: 'pound banknote' },
      { c: '💰', n: 'Мешок с деньгами', k: 'money bag' },
      { c: '🪙', n: 'Монета', k: 'coin' },
      { c: '💳', n: 'Карта', k: 'credit card' },
      { c: '💎', n: 'Бриллиант', k: 'gem stone' },
      { c: '⚖️', n: 'Весы', k: 'balance scale' },
      { c: '🪜', n: 'Лестница', k: 'ladder' },
      { c: '🧰', n: 'Ящик с инструментами', k: 'toolbox' },
      { c: '🪛', n: 'Отвёртка', k: 'screwdriver' },
      { c: '🔧', n: 'Ключ', k: 'wrench' },
      { c: '🔨', n: 'Молоток', k: 'hammer' },
      { c: '⚒️', n: 'Молот и кирка', k: 'hammer and pick' },
      { c: '🛠️', n: 'Инструменты', k: 'hammer and wrench tools' },
      { c: '⛏️', n: 'Кирка', k: 'pick' },
      { c: '🪓', n: 'Топор', k: 'axe' },
      { c: '🪚', n: 'Пила', k: 'carpentry saw' },
      { c: '🔩', n: 'Болт', k: 'nut and bolt' },
      { c: '⚙️', n: 'Шестерня', k: 'gear settings' },
      { c: '🧱', n: 'Кирпич', k: 'brick' },
      { c: '🪤', n: 'Мышеловка', k: 'mouse trap' },
      { c: '🧲', n: 'Магнит', k: 'magnet' },
      { c: '🔫', n: 'Водяной пистолет', k: 'water pistol' },
      { c: '💣', n: 'Бомба', k: 'bomb' },
      { c: '🧨', n: 'Петарда', k: 'firecracker' },
      { c: '🪓', n: 'Топор 2', k: 'axe2' },
      { c: '🔪', n: 'Нож', k: 'kitchen knife' },
      { c: '🗡️', n: 'Клинок', k: 'dagger' },
      { c: '⚔️', n: 'Скрещённые мечи', k: 'crossed swords' },
      { c: '🛡️', n: 'Щит', k: 'shield' },
      { c: '🚬', n: 'Сигарета', k: 'cigarette' },
      { c: '⚰️', n: 'Гроб', k: 'coffin' },
      { c: '🪦', n: 'Надгробие', k: 'headstone' },
      { c: '⚱️', n: 'Урна', k: 'funeral urn' },
      { c: '🏺', n: 'Амфора', k: 'amphora' },
      { c: '🔮', n: 'Хрустальный шар', k: 'crystal ball' },
      { c: '🧿', n: 'Назар', k: 'nazar amulet' },
      { c: '🪬', n: 'Хамса', k: 'hamsa' },
      { c: '📿', n: 'Чётки', k: 'prayer beads' },
      { c: '🧸', n: 'Мишка', k: 'teddy bear' },
      { c: '🪅', n: 'Пиньята', k: 'pinata' },
      { c: '🪆', n: 'Матрёшка', k: 'nesting dolls' },
      { c: '🖼️', n: 'Картина', k: 'framed picture' },
      { c: '🪞', n: 'Зеркало', k: 'mirror' },
      { c: '🪟', n: 'Окно', k: 'window' },
      { c: '🛏️', n: 'Кровать', k: 'bed' },
      { c: '🛋️', n: 'Диван', k: 'couch and lamp' },
      { c: '🪑', n: 'Стул', k: 'chair' },
      { c: '🚪', n: 'Дверь', k: 'door' },
      { c: '🪠', n: 'Вантуз', k: 'plunger' },
      { c: '🛁', n: 'Ванна', k: 'bathtub' },
      { c: '🛀', n: 'Купаться', k: 'person taking bath' },
      { c: '🚿', n: 'Душ', k: 'shower' },
      { c: '🧴', n: 'Бутылка с мылом', k: 'lotion bottle' },
      { c: '🧷', n: 'Английская булавка', k: 'safety pin' },
      { c: '🧹', n: 'Веник', k: 'broom' },
      { c: '🧺', n: 'Корзина', k: 'basket' },
      { c: '🧻', n: 'Туалетная бумага', k: 'roll of paper' },
      { c: '🪒', n: 'Бритва', k: 'razor' },
      { c: '🧼', n: 'Мыло', k: 'soap' },
      { c: '🪥', n: 'Зубная щётка', k: 'toothbrush' },
      { c: '🧽', n: 'Губка', k: 'sponge' },
      { c: '🪣', n: 'Ведро', k: 'bucket' },
      { c: '🧰', n: 'Ящик с инструментом', k: 'toolbox2' },
      { c: '🪥', n: 'Зубная щётка 2', k: 'toothbrush2' },
      { c: '🗝️', n: 'Старый ключ', k: 'old key' },
      { c: '🔑', n: 'Ключ', k: 'key' },
      { c: '🔒', n: 'Замок', k: 'locked lock' },
      { c: '🔓', n: 'Открытый замок', k: 'unlocked' },
      { c: '🔏', n: 'Замок и ручка', k: 'lock with pen' },
      { c: '🔐', n: 'Замок и ключ', k: 'lock with key' },
      { c: '✉️', n: 'Конверт', k: 'envelope' },
      { c: '📧', n: 'E-mail', k: 'email' },
      { c: '📨', n: 'Входящее письмо', k: 'incoming envelope' },
      { c: '📩', n: 'Письмо с уведомлением', k: 'envelope with arrow' },
      { c: '📤', n: 'Исходящие', k: 'outbox tray' },
      { c: '📥', n: 'Входящие', k: 'inbox tray' },
      { c: '📦', n: 'Посылка', k: 'package' },
      { c: '📫', n: 'Закрытый почтовый ящик', k: 'closed mailbox flag up' },
      { c: '📪', n: 'Пустой почтовый ящик', k: 'closed mailbox flag down' },
      { c: '📬', n: 'Открытый ящик', k: 'open mailbox flag up' },
      { c: '📭', n: 'Открытый пустой', k: 'open mailbox flag down' },
      { c: '📮', n: 'Почтовый ящик', k: 'postbox' },
      { c: '🗳️', n: 'Урна', k: 'ballot box' },
      { c: '📝', n: 'Записка', k: 'memo writing' },
      { c: '✏️', n: 'Карандаш', k: 'pencil' },
      { c: '✒️', n: 'Перо', k: 'black nib pen' },
      { c: '🖋️', n: 'Перьевая ручка', k: 'fountain pen' },
      { c: '🖊️', n: 'Ручка', k: 'pen' },
      { c: '🖌️', n: 'Кисточка', k: 'paintbrush' },
      { c: '🖍️', n: 'Восковой мелок', k: 'crayon' },
      { c: '📁', n: 'Папка', k: 'file folder' },
      { c: '📂', n: 'Открытая папка', k: 'open file folder' },
      { c: '🗂️', n: 'Картотека', k: 'card index dividers' },
      { c: '📅', n: 'Календарь', k: 'calendar' },
      { c: '📆', n: 'Отрывной календарь', k: 'tear off calendar' },
      { c: '🗒️', n: 'Блокнот на спирали', k: 'spiral notepad' },
      { c: '🗓️', n: 'Календарь на спирали', k: 'spiral calendar' },
      { c: '📇', n: 'Картотека-карта', k: 'card index' },
      { c: '📈', n: 'График растёт', k: 'chart increasing' },
      { c: '📉', n: 'График падает', k: 'chart decreasing' },
      { c: '📊', n: 'Гистограмма', k: 'bar chart' },
      { c: '📋', n: 'Планшет', k: 'clipboard' },
      { c: '📌', n: 'Кнопка', k: 'pushpin' },
      { c: '📍', n: 'Круглая кнопка', k: 'round pushpin' },
      { c: '📎', n: 'Скрепка', k: 'paperclip' },
      { c: '🖇️', n: 'Связка скрепок', k: 'linked paperclips' },
      { c: '📏', n: 'Линейка', k: 'straight ruler' },
      { c: '📐', n: 'Треугольник', k: 'triangular ruler' },
      { c: '✂️', n: 'Ножницы', k: 'scissors' },
      { c: '🗃️', n: 'Картотечный ящик', k: 'card file box' },
      { c: '🗄️', n: 'Шкаф', k: 'file cabinet' },
      { c: '🗑️', n: 'Корзина', k: 'wastebasket trash' },
      { c: '📄', n: 'Документ', k: 'page facing up document' },
      { c: '📃', n: 'Свиток', k: 'page with curl' },
      { c: '📑', n: 'Документ с закладкой', k: 'bookmark tabs' },
      { c: '🧾', n: 'Чек', k: 'receipt' },
      { c: '📜', n: 'Свиток', k: 'scroll' },
      { c: '📰', n: 'Газета', k: 'newspaper' },
      { c: '🗞️', n: 'Свёрнутая газета', k: 'rolled up newspaper' },
      { c: '📓', n: 'Тетрадь', k: 'notebook' },
      { c: '📔', n: 'Дневник', k: 'notebook with cover' },
      { c: '📒', n: 'Регистр', k: 'ledger' },
      { c: '📕', n: 'Красная книга', k: 'closed book red' },
      { c: '📗', n: 'Зелёная книга', k: 'green book' },
      { c: '📘', n: 'Синяя книга', k: 'blue book' },
      { c: '📙', n: 'Оранжевая книга', k: 'orange book' },
      { c: '📚', n: 'Книги', k: 'books' },
      { c: '📖', n: 'Открытая книга', k: 'open book' },
      { c: '🔖', n: 'Закладка', k: 'bookmark' },
      { c: '🧷', n: 'Булавка', k: 'safety pin 2' },
    ],
  },
  {
    id: 'symbols',
    title: 'Символы',
    icon: '🔣',
    items: [
      { c: '✅', n: 'Зелёная галочка', k: 'check mark button done' },
      { c: '☑️', n: 'Галочка в квадрате', k: 'check box' },
      { c: '✔️', n: 'Галочка', k: 'check mark' },
      { c: '❌', n: 'Крестик', k: 'cross mark' },
      { c: '❎', n: 'Крестик в квадрате', k: 'cross mark button' },
      { c: '➕', n: 'Плюс', k: 'plus' },
      { c: '➖', n: 'Минус', k: 'minus' },
      { c: '➗', n: 'Деление', k: 'divide' },
      { c: '✖️', n: 'Умножение', k: 'multiply' },
      { c: '🟰', n: 'Равно', k: 'heavy equals' },
      { c: '♾️', n: 'Бесконечность', k: 'infinity' },
      { c: '💯', n: 'Сто баллов', k: 'hundred points' },
      { c: '🔥', n: 'Огонь', k: 'fire2' },
      { c: '⚡', n: 'Молния', k: 'lightning' },
      { c: '💫', n: 'Звёздочка', k: 'dizzy' },
      { c: '🌀', n: 'Циклон', k: 'cyclone' },
      { c: '💢', n: 'Гнев', k: 'anger symbol' },
      { c: '💦', n: 'Брызги', k: 'sweat droplets' },
      { c: '💨', n: 'Пар', k: 'dashing away' },
      { c: '🕳️', n: 'Дыра', k: 'hole' },
      { c: '💬', n: 'Реплика', k: 'speech balloon' },
      { c: '🗨️', n: 'Левая реплика', k: 'left speech bubble' },
      { c: '🗯️', n: 'Кричащая реплика', k: 'right anger bubble' },
      { c: '💭', n: 'Мысль', k: 'thought balloon' },
      { c: '💤', n: 'Зззз', k: 'zzz sleep' },
      { c: 'ℹ️', n: 'Инфо', k: 'information' },
      { c: '❓', n: 'Вопросительный знак', k: 'question mark' },
      { c: '❔', n: 'Белый вопрос', k: 'white question' },
      { c: '❗', n: 'Восклицание', k: 'exclamation' },
      { c: '❕', n: 'Белое восклицание', k: 'white exclamation' },
      { c: '‼️', n: 'Двойное восклицание', k: 'double exclamation' },
      { c: '⁉️', n: 'Восклицание и вопрос', k: 'exclamation question' },
      { c: '🔅', n: 'Тусклая яркость', k: 'dim button' },
      { c: '🔆', n: 'Яркость', k: 'bright button' },
      { c: '🔇', n: 'Без звука', k: 'muted speaker' },
      { c: '🔈', n: 'Низкая громкость', k: 'speaker low volume' },
      { c: '🔉', n: 'Средняя громкость', k: 'speaker medium' },
      { c: '🔊', n: 'Высокая громкость', k: 'speaker high' },
      { c: '🔔', n: 'Колокольчик', k: 'bell' },
      { c: '🔕', n: 'Без звука колокольчик', k: 'bell with slash' },
      { c: '📣', n: 'Мегафон', k: 'megaphone' },
      { c: '📢', n: 'Громкоговоритель', k: 'loudspeaker' },
      { c: '🔁', n: 'Повтор', k: 'repeat' },
      { c: '🔂', n: 'Повтор один', k: 'repeat single' },
      { c: '🔀', n: 'Перемешать', k: 'shuffle' },
      { c: '▶️', n: 'Воспроизвести', k: 'play' },
      { c: '⏩', n: 'Перемотка вперёд', k: 'fast forward' },
      { c: '⏪', n: 'Перемотка назад', k: 'fast reverse' },
      { c: '⏫', n: 'Быстро вверх', k: 'fast up' },
      { c: '⏬', n: 'Быстро вниз', k: 'fast down' },
      { c: '⏭️', n: 'Следующий', k: 'next track' },
      { c: '⏮️', n: 'Предыдущий', k: 'previous track' },
      { c: '⏯️', n: 'Пауза/воспр.', k: 'play pause' },
      { c: '⏸️', n: 'Пауза', k: 'pause' },
      { c: '⏹️', n: 'Стоп', k: 'stop button' },
      { c: '⏺️', n: 'Запись', k: 'record' },
      { c: '⏏️', n: 'Извлечь', k: 'eject' },
      { c: '🔼', n: 'Стрелка вверх', k: 'upwards button' },
      { c: '🔽', n: 'Стрелка вниз', k: 'downwards button' },
      { c: '⬆️', n: 'Вверх', k: 'up arrow' },
      { c: '⬇️', n: 'Вниз', k: 'down arrow' },
      { c: '⬅️', n: 'Влево', k: 'left arrow' },
      { c: '➡️', n: 'Вправо', k: 'right arrow' },
      { c: '↗️', n: 'Вверх-вправо', k: 'up right arrow' },
      { c: '↘️', n: 'Вниз-вправо', k: 'down right arrow' },
      { c: '↙️', n: 'Вниз-влево', k: 'down left arrow' },
      { c: '↖️', n: 'Вверх-влево', k: 'up left arrow' },
      { c: '↕️', n: 'Вверх-вниз', k: 'up down arrow' },
      { c: '↔️', n: 'Влево-вправо', k: 'left right arrow' },
      { c: '↩️', n: 'Возврат влево', k: 'right arrow curving left' },
      { c: '↪️', n: 'Возврат вправо', k: 'left arrow curving right' },
      { c: '⤴️', n: 'Стрелка вверх дуга', k: 'right arrow curving up' },
      { c: '⤵️', n: 'Стрелка вниз дуга', k: 'right arrow curving down' },
      { c: '🔃', n: 'По часовой', k: 'clockwise vertical arrows' },
      { c: '🔄', n: 'Против часовой', k: 'anticlockwise arrows' },
      { c: '🆗', n: 'OK', k: 'ok button' },
      { c: '🆕', n: 'NEW', k: 'new button' },
      { c: '🆙', n: 'UP!', k: 'up button' },
      { c: '🆒', n: 'COOL', k: 'cool button' },
      { c: '🆓', n: 'FREE', k: 'free button' },
      { c: '🔝', n: 'TOP', k: 'top arrow' },
      { c: '🔚', n: 'END', k: 'end arrow' },
      { c: '🔙', n: 'BACK', k: 'back arrow' },
      { c: '🔛', n: 'ON!', k: 'on arrow' },
      { c: '🔜', n: 'SOON', k: 'soon arrow' },
      { c: '#️⃣', n: 'Решётка', k: 'keycap hash' },
      { c: '*️⃣', n: 'Звёздочка', k: 'keycap star' },
      { c: '0️⃣', n: '0', k: 'keycap 0' },
      { c: '1️⃣', n: '1', k: 'keycap 1' },
      { c: '2️⃣', n: '2', k: 'keycap 2' },
      { c: '3️⃣', n: '3', k: 'keycap 3' },
      { c: '4️⃣', n: '4', k: 'keycap 4' },
      { c: '5️⃣', n: '5', k: 'keycap 5' },
      { c: '6️⃣', n: '6', k: 'keycap 6' },
      { c: '7️⃣', n: '7', k: 'keycap 7' },
      { c: '8️⃣', n: '8', k: 'keycap 8' },
      { c: '9️⃣', n: '9', k: 'keycap 9' },
      { c: '🔟', n: '10', k: 'keycap 10' },
      { c: '♻️', n: 'Переработка', k: 'recycling' },
      { c: '⚜️', n: 'Лилия', k: 'fleur de lis' },
      { c: '✳️', n: 'Восьмиконечная звезда', k: 'eight spoked asterisk' },
      { c: '✴️', n: 'Восьмиконечная звезда 2', k: 'eight pointed star' },
      { c: '❇️', n: 'Искра', k: 'sparkle' },
      { c: '🚸', n: 'Дети на дороге', k: 'children crossing' },
      { c: '⚠️', n: 'Внимание', k: 'warning' },
      { c: '☢️', n: 'Радиация', k: 'radioactive' },
      { c: '☣️', n: 'Биоопасность', k: 'biohazard' },
      { c: '🔞', n: '18+', k: 'no one under eighteen' },
      { c: '🚫', n: 'Запрещено', k: 'prohibited' },
      { c: '🚭', n: 'Не курить', k: 'no smoking' },
      { c: '⛔', n: 'Въезд запрещён', k: 'no entry' },
      { c: '📵', n: 'Без телефона', k: 'no mobile phones' },
      { c: '⭕', n: 'Большой круг', k: 'hollow red circle' },
      { c: '⚛️', n: 'Атом', k: 'atom symbol' },
      { c: '☪️', n: 'Полумесяц', k: 'star and crescent' },
      { c: '☯️', n: 'Инь-Ян', k: 'yin yang' },
      { c: '✝️', n: 'Крест', k: 'cross latin' },
      { c: '☦️', n: 'Православный крест', k: 'orthodox cross' },
      { c: '☮️', n: 'Мир', k: 'peace symbol' },
      { c: '🕎', n: 'Менора', k: 'menorah' },
      { c: '🔯', n: 'Звезда Давида', k: 'dotted six pointed star' },
      { c: '♈', n: 'Овен', k: 'aries' },
      { c: '♉', n: 'Телец', k: 'taurus' },
      { c: '♊', n: 'Близнецы', k: 'gemini' },
      { c: '♋', n: 'Рак', k: 'cancer' },
      { c: '♌', n: 'Лев', k: 'leo' },
      { c: '♍', n: 'Дева', k: 'virgo' },
      { c: '♎', n: 'Весы', k: 'libra' },
      { c: '♏', n: 'Скорпион', k: 'scorpio' },
      { c: '♐', n: 'Стрелец', k: 'sagittarius' },
      { c: '♑', n: 'Козерог', k: 'capricorn' },
      { c: '♒', n: 'Водолей', k: 'aquarius' },
      { c: '♓', n: 'Рыбы', k: 'pisces' },
      { c: '⛎', n: 'Змееносец', k: 'ophiuchus' },
      { c: '🔴', n: 'Красный круг', k: 'red circle' },
      { c: '🟠', n: 'Оранжевый круг', k: 'orange circle' },
      { c: '🟡', n: 'Жёлтый круг', k: 'yellow circle' },
      { c: '🟢', n: 'Зелёный круг', k: 'green circle' },
      { c: '🔵', n: 'Синий круг', k: 'blue circle' },
      { c: '🟣', n: 'Фиолетовый круг', k: 'purple circle' },
      { c: '⚫', n: 'Чёрный круг', k: 'black circle' },
      { c: '⚪', n: 'Белый круг', k: 'white circle' },
      { c: '🟤', n: 'Коричневый круг', k: 'brown circle' },
      { c: '🟥', n: 'Красный квадрат', k: 'red square' },
      { c: '🟧', n: 'Оранжевый квадрат', k: 'orange square' },
      { c: '🟨', n: 'Жёлтый квадрат', k: 'yellow square' },
      { c: '🟩', n: 'Зелёный квадрат', k: 'green square' },
      { c: '🟦', n: 'Синий квадрат', k: 'blue square' },
      { c: '🟪', n: 'Фиолетовый квадрат', k: 'purple square' },
      { c: '⬛', n: 'Чёрный квадрат', k: 'black large square' },
      { c: '⬜', n: 'Белый квадрат', k: 'white large square' },
      { c: '🟫', n: 'Коричневый квадрат', k: 'brown square' },
      { c: '◼️', n: 'Чёрный средний', k: 'black medium square' },
      { c: '◻️', n: 'Белый средний', k: 'white medium square' },
      { c: '◾', n: 'Чёрный малый', k: 'black small square' },
      { c: '◽', n: 'Белый малый', k: 'white small square' },
      { c: '🔶', n: 'Оранжевый ромб', k: 'large orange diamond' },
      { c: '🔷', n: 'Синий ромб', k: 'large blue diamond' },
      { c: '🔸', n: 'Малый оранжевый ромб', k: 'small orange diamond' },
      { c: '🔹', n: 'Малый синий ромб', k: 'small blue diamond' },
      { c: '🔺', n: 'Треугольник вверх', k: 'red triangle pointed up' },
      { c: '🔻', n: 'Треугольник вниз', k: 'red triangle pointed down' },
      { c: '🔘', n: 'Радио-кнопка', k: 'radio button' },
      { c: '🔳', n: 'Белый рамочный квадрат', k: 'white square button' },
      { c: '🔲', n: 'Чёрный рамочный квадрат', k: 'black square button' },
    ],
  },
  {
    id: 'flags',
    title: 'Флаги',
    icon: '🏳️',
    items: [
      { c: '🏳️', n: 'Белый флаг', k: 'white flag' },
      { c: '🏴', n: 'Чёрный флаг', k: 'black flag' },
      { c: '🏁', n: 'Финиш', k: 'chequered flag' },
      { c: '🚩', n: 'Треугольный флаг', k: 'triangular flag' },
      { c: '🏳️‍🌈', n: 'Радужный флаг', k: 'rainbow flag pride' },
      { c: '🏳️‍⚧️', n: 'Трансгендерный флаг', k: 'transgender flag' },
      { c: '🏴‍☠️', n: 'Пиратский флаг', k: 'pirate flag' },
      { c: '🇷🇺', n: 'Россия', k: 'russia ru' },
      { c: '🇧🇾', n: 'Беларусь', k: 'belarus by' },
      { c: '🇺🇦', n: 'Украина', k: 'ukraine ua' },
      { c: '🇰🇿', n: 'Казахстан', k: 'kazakhstan kz' },
      { c: '🇺🇸', n: 'США', k: 'usa us america' },
      { c: '🇬🇧', n: 'Великобритания', k: 'uk gb united kingdom' },
      { c: '🇪🇺', n: 'ЕС', k: 'eu european union' },
      { c: '🇩🇪', n: 'Германия', k: 'germany de' },
      { c: '🇫🇷', n: 'Франция', k: 'france fr' },
      { c: '🇮🇹', n: 'Италия', k: 'italy it' },
      { c: '🇪🇸', n: 'Испания', k: 'spain es' },
      { c: '🇵🇹', n: 'Португалия', k: 'portugal pt' },
      { c: '🇨🇭', n: 'Швейцария', k: 'switzerland ch' },
      { c: '🇦🇹', n: 'Австрия', k: 'austria at' },
      { c: '🇳🇱', n: 'Нидерланды', k: 'netherlands nl' },
      { c: '🇧🇪', n: 'Бельгия', k: 'belgium be' },
      { c: '🇸🇪', n: 'Швеция', k: 'sweden se' },
      { c: '🇳🇴', n: 'Норвегия', k: 'norway no' },
      { c: '🇫🇮', n: 'Финляндия', k: 'finland fi' },
      { c: '🇩🇰', n: 'Дания', k: 'denmark dk' },
      { c: '🇮🇸', n: 'Исландия', k: 'iceland is' },
      { c: '🇮🇪', n: 'Ирландия', k: 'ireland ie' },
      { c: '🇵🇱', n: 'Польша', k: 'poland pl' },
      { c: '🇨🇿', n: 'Чехия', k: 'czech cz' },
      { c: '🇸🇰', n: 'Словакия', k: 'slovakia sk' },
      { c: '🇭🇺', n: 'Венгрия', k: 'hungary hu' },
      { c: '🇷🇴', n: 'Румыния', k: 'romania ro' },
      { c: '🇬🇷', n: 'Греция', k: 'greece gr' },
      { c: '🇹🇷', n: 'Турция', k: 'turkey tr' },
      { c: '🇮🇱', n: 'Израиль', k: 'israel il' },
      { c: '🇦🇪', n: 'ОАЭ', k: 'uae ae' },
      { c: '🇸🇦', n: 'Саудовская Аравия', k: 'saudi arabia sa' },
      { c: '🇪🇬', n: 'Египет', k: 'egypt eg' },
      { c: '🇿🇦', n: 'ЮАР', k: 'south africa za' },
      { c: '🇮🇳', n: 'Индия', k: 'india in' },
      { c: '🇨🇳', n: 'Китай', k: 'china cn' },
      { c: '🇯🇵', n: 'Япония', k: 'japan jp' },
      { c: '🇰🇷', n: 'Южная Корея', k: 'south korea kr' },
      { c: '🇰🇵', n: 'Северная Корея', k: 'north korea kp' },
      { c: '🇹🇼', n: 'Тайвань', k: 'taiwan tw' },
      { c: '🇭🇰', n: 'Гонконг', k: 'hong kong hk' },
      { c: '🇸🇬', n: 'Сингапур', k: 'singapore sg' },
      { c: '🇹🇭', n: 'Таиланд', k: 'thailand th' },
      { c: '🇻🇳', n: 'Вьетнам', k: 'vietnam vn' },
      { c: '🇮🇩', n: 'Индонезия', k: 'indonesia id' },
      { c: '🇲🇾', n: 'Малайзия', k: 'malaysia my' },
      { c: '🇵🇭', n: 'Филиппины', k: 'philippines ph' },
      { c: '🇦🇺', n: 'Австралия', k: 'australia au' },
      { c: '🇳🇿', n: 'Новая Зеландия', k: 'new zealand nz' },
      { c: '🇨🇦', n: 'Канада', k: 'canada ca' },
      { c: '🇲🇽', n: 'Мексика', k: 'mexico mx' },
      { c: '🇧🇷', n: 'Бразилия', k: 'brazil br' },
      { c: '🇦🇷', n: 'Аргентина', k: 'argentina ar' },
      { c: '🇨🇱', n: 'Чили', k: 'chile cl' },
      { c: '🇨🇴', n: 'Колумбия', k: 'colombia co' },
      { c: '🇵🇪', n: 'Перу', k: 'peru pe' },
      { c: '🇻🇪', n: 'Венесуэла', k: 'venezuela ve' },
      { c: '🇨🇺', n: 'Куба', k: 'cuba cu' },
      { c: '🇯🇲', n: 'Ямайка', k: 'jamaica jm' },
    ],
  },
];

// Все эмодзи плоским списком — для случайного выбора и быстрого поиска.
export const ALL_EMOJIS: Emoji[] = EMOJI_CATEGORIES.flatMap((c) => c.items);
