import type { DocumentItem, DocumentSection } from './types';

export const SECTIONS: DocumentSection[] = [
  {
    id: 'clients',
    title: 'Документы по клиентам',
    emoji: '🏢',
    description: 'Договоры, NDA, спецификации и переписка по заказчикам.',
  },
  {
    id: 'regulations',
    title: 'Регламенты работы',
    emoji: '📘',
    description: 'Внутренние процессы, инструкции и SLA команды.',
  },
  {
    id: 'company',
    title: 'Документы по компании',
    emoji: '🏛️',
    description: 'Устав, лицензии, реквизиты и учредительные документы.',
  },
  {
    id: 'employees',
    title: 'Документы по сотрудникам',
    emoji: '👥',
    description: 'Кадровые документы, оферы, должностные инструкции.',
  },
  {
    id: 'contractors',
    title: 'Документы по исполнителям',
    emoji: '🤝',
    description: 'Договоры подряда, акты, портфолио внешних специалистов.',
  },
  {
    id: 'tender',
    title: 'Документы для тендера',
    emoji: '📋',
    description: 'Заявки, расчёты, презентации и сопровождение тендеров.',
  },
  {
    id: 'general',
    title: 'Общие документы',
    emoji: '📁',
    description: 'Шаблоны, лицензии и прочие материалы команды.',
  },
];

export const DOCUMENTS: DocumentItem[] = [
  // clients
  {
    id: 'd-cli-1',
    section: 'clients',
    title: 'Договор Sberbank — рамочный',
    emoji: '📄',
    kind: 'doc',
    updatedAt: '2026-05-18T10:14:00Z',
    owner: 'Анна Морозова',
    tags: ['договор', 'действующий'],
    description: 'Рамочный договор на оказание услуг по подбору персонала.',
  },
  {
    id: 'd-cli-2',
    section: 'clients',
    title: 'NDA — Яндекс',
    emoji: '🔒',
    kind: 'pdf',
    updatedAt: '2026-05-12T08:30:00Z',
    owner: 'Игорь Семёнов',
    tags: ['NDA'],
  },
  {
    id: 'd-cli-3',
    section: 'clients',
    title: 'Спецификация — Газпромнефть IT',
    emoji: '📑',
    kind: 'doc',
    updatedAt: '2026-05-05T15:42:00Z',
    owner: 'Анна Морозова',
    tags: ['спецификация', 'в работе'],
  },
  {
    id: 'd-cli-4',
    section: 'clients',
    title: 'Реестр заказчиков 2026',
    emoji: '📊',
    kind: 'xlsx',
    updatedAt: '2026-05-19T19:01:00Z',
    owner: 'Мария Лебедева',
    tags: ['реестр'],
  },

  // regulations
  {
    id: 'd-reg-1',
    section: 'regulations',
    title: 'Регламент работы с вакансией',
    emoji: '📘',
    kind: 'doc',
    updatedAt: '2026-04-22T12:00:00Z',
    owner: 'Команда LG',
    tags: ['процесс'],
    description: 'Этапы обработки вакансии — от заявки заказчика до закрытия.',
  },
  {
    id: 'd-reg-2',
    section: 'regulations',
    title: 'Регламент рекрутера',
    emoji: '🧭',
    kind: 'doc',
    updatedAt: '2026-04-10T09:20:00Z',
    owner: 'Команда LG',
    tags: ['HR'],
  },
  {
    id: 'd-reg-3',
    section: 'regulations',
    title: 'SLA по откликам и звонкам',
    emoji: '⏱️',
    kind: 'doc',
    updatedAt: '2026-03-30T17:00:00Z',
    owner: 'Команда LG',
  },
  {
    id: 'd-reg-4',
    section: 'regulations',
    title: 'Чек-лист интервью',
    emoji: '✅',
    kind: 'doc',
    updatedAt: '2026-05-02T11:11:00Z',
    owner: 'Команда LG',
  },

  // company
  {
    id: 'd-com-1',
    section: 'company',
    title: 'Устав LG Интеграция',
    emoji: '📜',
    kind: 'pdf',
    updatedAt: '2026-01-15T10:00:00Z',
    owner: 'Юр. отдел',
    tags: ['устав', 'учредительные'],
    description: 'Действующая редакция устава с последними изменениями.',
  },
  {
    id: 'd-com-2',
    section: 'company',
    title: 'Реквизиты компании',
    emoji: '🏛️',
    kind: 'doc',
    updatedAt: '2026-04-02T09:30:00Z',
    owner: 'Бухгалтерия',
    tags: ['реквизиты'],
  },
  {
    id: 'd-com-3',
    section: 'company',
    title: 'Свидетельство о регистрации',
    emoji: '📃',
    kind: 'pdf',
    updatedAt: '2026-02-10T12:00:00Z',
    owner: 'Юр. отдел',
  },
  {
    id: 'd-com-4',
    section: 'company',
    title: 'Финансовая отчётность 2025',
    emoji: '📊',
    kind: 'xlsx',
    updatedAt: '2026-03-25T14:20:00Z',
    owner: 'Финансы',
    tags: ['отчётность'],
  },
  {
    id: 'd-com-5',
    section: 'company',
    title: 'Структура компании',
    emoji: '🗂️',
    kind: 'pptx',
    updatedAt: '2026-05-05T11:00:00Z',
    owner: 'HR',
    tags: ['оргструктура'],
  },

  // employees
  {
    id: 'd-emp-1',
    section: 'employees',
    title: 'Шаблон трудового договора',
    emoji: '📝',
    kind: 'doc',
    updatedAt: '2026-02-15T10:00:00Z',
    owner: 'Юр. отдел',
    tags: ['шаблон'],
  },
  {
    id: 'd-emp-2',
    section: 'employees',
    title: 'Должностные инструкции',
    emoji: '📂',
    kind: 'folder',
    updatedAt: '2026-05-01T08:45:00Z',
    owner: 'HR',
  },
  {
    id: 'd-emp-3',
    section: 'employees',
    title: 'Список сотрудников 2026',
    emoji: '👥',
    kind: 'xlsx',
    updatedAt: '2026-05-15T14:00:00Z',
    owner: 'HR',
  },
  {
    id: 'd-emp-4',
    section: 'employees',
    title: 'Onboarding plan — новый рекрутер',
    emoji: '🚀',
    kind: 'doc',
    updatedAt: '2026-04-25T10:30:00Z',
    owner: 'HR',
  },

  // contractors
  {
    id: 'd-con-1',
    section: 'contractors',
    title: 'Договор подряда — шаблон',
    emoji: '📄',
    kind: 'doc',
    updatedAt: '2026-01-12T12:00:00Z',
    owner: 'Юр. отдел',
    tags: ['шаблон'],
  },
  {
    id: 'd-con-2',
    section: 'contractors',
    title: 'Акт выполненных работ',
    emoji: '🧾',
    kind: 'doc',
    updatedAt: '2026-05-11T16:20:00Z',
    owner: 'Бухгалтерия',
  },
  {
    id: 'd-con-3',
    section: 'contractors',
    title: 'Реестр внешних подрядчиков',
    emoji: '📒',
    kind: 'xlsx',
    updatedAt: '2026-05-18T09:00:00Z',
    owner: 'Мария Лебедева',
  },

  // tender
  {
    id: 'd-ten-1',
    section: 'tender',
    title: 'Тендер ВТБ — заявка',
    emoji: '📋',
    kind: 'doc',
    updatedAt: '2026-05-19T13:00:00Z',
    owner: 'Анна Морозова',
    tags: ['срочно'],
    description: 'Заявка на участие в тендере по подбору IT-специалистов.',
  },
  {
    id: 'd-ten-2',
    section: 'tender',
    title: 'Финансовый расчёт — Газпром',
    emoji: '💰',
    kind: 'xlsx',
    updatedAt: '2026-05-17T11:30:00Z',
    owner: 'Финансы',
  },
  {
    id: 'd-ten-3',
    section: 'tender',
    title: 'Презентация для клиента',
    emoji: '🎯',
    kind: 'pptx',
    updatedAt: '2026-05-14T18:00:00Z',
    owner: 'Игорь Семёнов',
  },
  {
    id: 'd-ten-4',
    section: 'tender',
    title: 'Чек-лист подготовки к тендеру',
    emoji: '✅',
    kind: 'doc',
    updatedAt: '2026-04-30T10:00:00Z',
    owner: 'Команда LG',
  },

  // general
  {
    id: 'd-gen-1',
    section: 'general',
    title: 'Бренд-бук LG',
    emoji: '🎨',
    kind: 'pdf',
    updatedAt: '2026-03-01T09:00:00Z',
    owner: 'Маркетинг',
    tags: ['брендинг'],
  },
  {
    id: 'd-gen-2',
    section: 'general',
    title: 'Лицензии и сертификаты',
    emoji: '📜',
    kind: 'folder',
    updatedAt: '2026-02-20T10:00:00Z',
    owner: 'Юр. отдел',
  },
  {
    id: 'd-gen-3',
    section: 'general',
    title: 'Шаблоны e-mail',
    emoji: '✉️',
    kind: 'doc',
    updatedAt: '2026-05-08T15:00:00Z',
    owner: 'Команда LG',
  },
];
